The World Band > [Life expectancy at birth, total](https://data.worldbank.org/indicator/SP.DYN.LE00.IN)<br />
The World Band > [Life expectancy at birth, male](https://data.worldbank.org/indicator/SP.DYN.LE00.MA.IN)<br />
The World Band > [Life expectancy at birth, female](https://data.worldbank.org/indicator/SP.DYN.LE00.FE.IN)<br />
[World Development Indicators > Life expectancy at birth](https://databank.worldbank.org/reports.aspx?source=2&series=SP.DYN.LE00.IN&country=) *(databank.worldbank.org)*<br />
[OECD stat](https://stats.oecd.org/index.aspx?queryid=30114)

"[Список стран по ожидаемой продолжительности жизни](https://ru.wikipedia.org/wiki/Список_стран_по_ожидаемой_продолжительности_жизни)"<br />
"[Продолжительность жизни в субъектах Российской Федерации](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_субъектах_Российской_Федерации)"<br />
[Таблица подбора цветов](http://mal-bioit.ru/survey-web-colors)<br />
[Список государств и зависимых территорий по населению](https://ru.wikipedia.org/wiki/Список_государств_и_зависимых_территорий_по_населению)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
pd.options.display.max_rows = 300

DESTINATION_OUTPUT = ''  # to where table code should be placed: 'file', 'here' or just print 'Done'

In [3]:
def output_table_code(st, file_name='', destination=''):
    if not destination:
        destination = DESTINATION_OUTPUT
        
    if destination == 'file':
        with open('output/'+file_name, 'w', encoding="utf-8") as fh:
            fh.write(st)
        print('Data has written to file')
    elif destination == 'here':
        print(st)
    else:
        print('done')

In [4]:
# create code for placing info in Wikipedia
def create_table(df, lang='en'):

    if lang=='ru':
        file_header='wbg_stats_header_2020_ru.txt'
        ptn_1 = 'флагификация'
        ptn_2 = 'флаг'
        prettify_name = {
            'European Union': '[[Европейский союз]]',
            'Central Europe and the Baltics': '[[Центральная Европа]] и [[Прибалтика]]',
            'Europe & Central Asia': '[[Европа]] и [[Центральная Азия]]',
            'South Asia': '[[Южная Азия]]',
            'East Asia & Pacific': '[[Восточная Азия]] и [[Австралия и Океания|Океания]]',
            'Middle East & North Africa': '[[Страны MENA|Ближний Восток и Северная Африка]]',
            'Africa Eastern and Southern': '[[Восточная Африка|Восточная]] и [[Южная Африка|Южная]] Африка',
            'Sub-Saharan Africa': '[[Чёрная Африка|Африка к югу от Сахары]]',
            'Africa Western and Central': '[[Западная Африка|Западная]] и [[Центральная Африка|Центральная]] Африка',
            'North America': '[[Северная Америка]]',
            'Latin America & Caribbean': '[[Латинская Америка]] и [[Антильские острова|Карибы]]',
            'Arab World': 'Арабский мир',
            'World': 'Мир',
            'Caribbean small states': '[[Список стран Карибского бассейна|Малые страны Карибского бассейна]]',
            'Pacific island small states': 'Малые страны на островах Тихого океана',
            'Small states': 'Малые страны',
            'Other small states': 'Другие малые страны'
        }
    else:
        file_header='wbg_stats_header_2020_en.txt'
        ptn_1 = 'flaglist'
        ptn_2 = 'flagicon'
        prettify_name = {
            'European Union': '[[European Union]]',
            'Central Europe and the Baltics': '[[Central Europe]] & the [[Baltic states|Baltics]]',
            'Europe & Central Asia': '[[Europe]] & [[Central Asia]]',
            'South Asia': '[[South Asia]]',
            'East Asia & Pacific': '[[Asia-Pacific|East Asia & Pacific]]',
            'Middle East & North Africa': '[[MENA|Middle East & North Africa]]',
            'Africa Eastern and Southern': 'Africa [[East Africa|Eastern]] & [[Southern Africa|Southern]]',
            'Sub-Saharan Africa': '[[Sub-Saharan Africa]]',
            'Africa Western and Central': 'Africa [[West Africa|Western]] & [[Central Africa|Central]]',
            'North America': '[[North America]]',
            'Latin America & Caribbean': '[[Latin America and the Caribbean|Latin America & Caribbean]]'
        }
        
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st = fh.read()
        
    st = st[:-1]
        
    for i in range(len(df)):
        ser = df.iloc[i]
        if ser.name in ['World',
                        'European Union', 'Central Europe and the Baltics',
                        'Europe & Central Asia',
                        'South Asia',
                        'East Asia & Pacific',
                        'Middle East & North Africa',
                        'Africa Eastern and Southern', 'Sub-Saharan Africa', 'Africa Western and Central',
                        'North America', 'Latin America & Caribbean']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|align=center| \'\'\'{prettify_name.get(ser.name, ser.name)}\'\'\' ' + \
                  f'||style="text-align:center; background:#e0ffd8;"| \'\'\'{ser.total:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| \'\'\'{ser.male:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#fee7f6;"| \'\'\'{ser.female:0.2f}\'\'\' ' + \
                  f'||style="text-align:center;"| \'\'\'{ser.gender_gap:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#e0ffd8; border-left-width:2px;"| \'\'\'{ser.Δ_2019_total:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| \'\'\'{ser.Δ_2019_male:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#fee7f6;"| \'\'\'{ser.Δ_2019_female:0.2f}\'\'\' ' + \
                  f'||style="text-align:center;"| \'\'\'{ser.Δ_2019_gender_gap:0.2f}\'\'\''
        elif ser.name in ['Caribbean small states',
                          'Pacific island small states',
                          'Small states',
                          'Other small states']:
            st += '\n' + '|-\n' + \
                  f'|style="text-align:left; padding-left: 35px;"|{prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="text-align:center; background:#e0ffd8;"| {ser.total:0.2f} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {ser.male:0.2f} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {ser.female:0.2f} ' + \
                  f'||style="text-align:center;"| {ser.gender_gap:0.2f} ' + \
                  f'||style="text-align:center; background:#e0ffd8; border-left-width:2px;"| {ser.Δ_2019_total:0.2f} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {ser.Δ_2019_male:0.2f} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {ser.Δ_2019_female:0.2f} ' + \
                  f'||style="text-align:center;"| {ser.Δ_2019_gender_gap:0.2f}'
        else:
            st += '\n' + '|-\n' + \
                  f'|align=left|{{{{{ptn_1}|{ser.name}}}}} ' + \
                  f'||style="text-align:center; background:#e0ffd8;"| {ser.total:0.2f} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {ser.male:0.2f} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {ser.female:0.2f} ' + \
                  f'||style="text-align:center;"| {ser.gender_gap:0.2f} ' + \
                  f'||style="text-align:center; background:#e0ffd8; border-left-width:2px;"| {ser.Δ_2019_total:0.2f} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {ser.Δ_2019_male:0.2f} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {ser.Δ_2019_female:0.2f} ' + \
                  f'||style="text-align:center;"| {ser.Δ_2019_gender_gap:0.2f}'
    st += '\n|}'
    return st

In [5]:
def extract_data_for_year(df, year='2019'):
    ls_dropping = [
        'Hong Kong SAR, China',
        'Macao SAR, China',
        'St. Martin (French part)',
        'New Caledonia',
        'Virgin Islands (U.S.)',
        'Channel Islands',
        'Faroe Islands',
        'West Bank and Gaza',
        'Kosovo',
        'Euro area',
        'IBRD only',
        'IDA & IBRD total',
        'IDA total',
        'IDA blend',
        'IDA only',
        'OECD members',
        'Europe & Central Asia (excluding high income)',
        'East Asia & Pacific (excluding high income)',
        'Latin America & Caribbean (excluding high income)',
        'Middle East & North Africa (excluding high income)',
        'Sub-Saharan Africa (excluding high income)',
        'East Asia & Pacific (IDA & IBRD countries)',
        'Europe & Central Asia (IDA & IBRD countries)',
        'Middle East & North Africa (IDA & IBRD countries)',
        'Sub-Saharan Africa (IDA & IBRD countries)',           
        'Latin America & the Caribbean (IDA & IBRD countries)',
        'South Asia (IDA & IBRD)',
        'Heavily indebted poor countries (HIPC)',
        'Fragile and conflict affected situations',
        'Least developed countries: UN classification',
        'Early-demographic dividend',
        'Late-demographic dividend',
        'Pre-demographic dividend',
        'Post-demographic dividend',
        'Low income',
        'Lower middle income',
        'Low & middle income',
        'Middle income',
        'Upper middle income',
        'High income'
    ]
    
    ser = df.drop(ls_dropping) \
            [str(year)] \
            .dropna() \
            .rename(index = {'United States':'USA',
                             'Russian Federation': 'Russia',
                             'Korea, Rep.': 'South Korea',
                             'Egypt, Arab Rep.': 'Egypt',
                             'Congo, Dem. Rep.': 'Congo, Democratic Republic of',
                             'Congo, Rep.': 'Congo, Republic of',
                             'Yemen, Rep.': 'Yemen',
                             'Micronesia, Fed. Sts.': 'Micronesia',
                             'Gambia, The': 'Gambia',
                             'Iran, Islamic Rep.': 'Iran',
                             "Korea, Dem. People's Rep.": 'North Korea',
                             'Syrian Arab Republic': 'Syria',
                             'Venezuela, RB': 'Venezuela',
                             'Kyrgyz Republic': 'Kyrgyzstan',
                             'Lao PDR': 'Laos',
                             'Czech Republic': 'Czechia',
                             'Slovak Republic': 'Slovakia',
                             'Bahamas, The': 'Bahamas',
                             'Brunei Darussalam': 'Brunei',
                             'St. Lucia': 'Saint Lucia',
                             'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines'
                            })
    
    return ser

In [6]:
df = pd.read_csv('data/World_Bank_Group-total.csv', skiprows=4, index_col=0)

ser_2020_total = extract_data_for_year(df, 2020)
ser_2020_total.name = '2020_total'

ser_2019_total = extract_data_for_year(df, 2019)
ser_2019_total.name = '2019_total'

del df

print(f"2020-total: {len(ser_2020_total)} records")
print(f"2019-total: {len(ser_2019_total)} records")

2020-total: 207 records
2019-total: 207 records

In [7]:
df = pd.read_csv('data/World_Bank_Group-male.csv', skiprows=4, index_col=0)

ser_2020_male = extract_data_for_year(df, 2020)
ser_2020_male.name = '2020_male'

ser_2019_male = extract_data_for_year(df, 2019)
ser_2019_male.name = '2019_male'

del df

print(f"2020-male: {len(ser_2020_male)} records")
print(f"2019-male: {len(ser_2019_male)} records")

2020-male: 207 records
2019-male: 207 records

In [8]:
df = pd.read_csv('data/World_Bank_Group-female.csv', skiprows=4, index_col=0)

ser_2020_female = extract_data_for_year(df, 2020)
ser_2020_female.name = '2020_female'

ser_2019_female = extract_data_for_year(df, 2019)
ser_2019_female.name = '2019_female'

del df

print(f"2020-female: {len(ser_2020_female)} records")
print(f"2019-female: {len(ser_2019_female)} records")

2020-female: 207 records
2019-female: 207 records

In [9]:
df = pd.concat([ser_2020_total, ser_2020_male, ser_2020_female, ser_2019_total, ser_2019_male, ser_2019_female],
               axis='columns', join='outer')
df.index.name = ''

print(df.shape)
df.loc[['World', 'Russia']]

(207, 6)

        2020_total  2020_male  2020_female  2019_total  2019_male  2019_female

World    72.747303  70.572878    75.062444   72.762667  70.598106    75.068109
Russia   71.338780  66.490000    76.430000   73.083902  68.240000    78.170000

In [10]:
df = pd.concat([ser_2020_total,
                ser_2020_male,
                ser_2020_female,
                ser_2020_female - ser_2020_male,
                ser_2020_total - ser_2019_total,
                ser_2020_male - ser_2019_male,
                ser_2020_female - ser_2019_female,
                ser_2020_female - ser_2020_male - ser_2019_female + ser_2019_male
               ], axis='columns', join='outer')

df.rename(columns={'2020_total': 'total',
                   '2020_male': 'male',
                   '2020_female': 'female',
                   0: 'gender_gap',
                   1: 'Δ_2019_total',
                   2: 'Δ_2019_male',
                   3: 'Δ_2019_female',
                   4: 'Δ_2019_gender_gap'}, inplace=True)
df.index.name = ''

df.sort_values(by='total', ascending=False, inplace=True)

print(df.shape)
df.loc[['World', 'Russia']]

(207, 8)

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
World,72.747303,70.572878,75.062444,4.489566,-0.015364,-0.025228,-0.005665,0.019563
Russia,71.338780,66.490000,76.430000,9.940000,-1.745122,-1.750000,-1.740000,0.010000

<br />
<br />
<br />

In [11]:
dd_S_America = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador',
                'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela',
                'World']

df_S_America = df.loc[dd_S_America]  \
                 .sort_values(by='total', ascending=False)
df_S_America

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Chile,80.329000,77.990000,82.522000,4.532000,0.148000,0.219000,0.080000,-0.139000
Uruguay,78.056000,74.290000,81.595000,7.305000,0.145000,0.171000,0.117000,-0.054000
Colombia,77.460000,74.720000,80.173000,5.453000,0.173000,0.192000,0.154000,-0.038000
Ecuador,77.216000,74.504000,80.023000,5.519000,0.206000,0.222000,0.185000,-0.037000
Peru,76.947000,74.288000,79.714000,5.426000,0.211000,0.228000,0.207000,-0.021000
Argentina,76.813000,73.405000,80.122000,6.717000,0.146000,0.163000,0.127000,-0.036000
Brazil,76.084000,72.463000,79.736000,7.273000,0.203000,0.220000,0.181000,-0.039000
Paraguay,74.363000,72.356000,76.524000,4.168000,0.109000,0.093000,0.128000,0.035000
World,72.747303,70.572878,75.062444,4.489566,-0.015364,-0.025228,-0.005665,0.019563
Venezuela,72.066000,68.324000,76.000000,7.676000,0.002000,-0.003000,-0.004000,-0.001000
Suriname,71.802000,68.577000,75.195000,6.618000,0.120000,0.109000,0.132000,0.023000
Bolivia,71.771000,68.927000,74.780000,5.853000,0.258000,0.243000,0.272000,0.029000
Guyana,70.023000,67.042000,73.219000,6.177000,0.117000,0.115000,0.124000,0.009000

In [12]:
table_code_S_America = create_table(df_S_America)
output_table_code(table_code_S_America, 'Table code WBG -2020 -S_America -en.txt', destination='file')

Data has written to file

In [13]:
table_code_S_America = create_table(df_S_America, lang='ru')
output_table_code(table_code_S_America, 'Table code WBG -2020 -S_America -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [14]:
dd_Asia = ['Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia', 'China', 'Cyprus', 'Egypt',
           'Georgia', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'North Korea', 'South Korea',
           'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal', 'Oman', 'Pakistan',
           'Philippines', 'Qatar', 'Russia', 'Saudi Arabia', 'Singapore', 'Sri Lanka', 'Syria', 'Tajikistan', 'Thailand', 'Timor-Leste',
           'Turkey', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen',
           'World', 'Europe & Central Asia', 'South Asia', 'East Asia & Pacific', 'Middle East & North Africa']

df_Asia = df.loc[dd_Asia]   \
            .sort_values(by='total', ascending=False)
df_Asia

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Japan,84.615610,81.640000,87.740000,6.100000,0.259268,0.230000,0.290000,0.060000
Singapore,83.743902,81.500000,86.100000,4.600000,0.148780,0.100000,0.200000,0.100000
South Korea,83.426829,80.500000,86.500000,6.000000,0.200000,0.200000,0.200000,0.000000
Israel,82.700000,80.700000,84.800000,4.100000,-0.104878,-0.300000,0.100000,0.400000
Cyprus,81.135000,79.103000,83.151000,4.048000,0.153000,0.182000,0.119000,-0.063000
Qatar,80.363000,79.314000,82.146000,2.832000,0.136000,0.172000,0.136000,-0.036000
Maldives,79.208000,77.816000,81.036000,3.220000,0.287000,0.293000,0.257000,-0.036000
Lebanon,79.004000,77.224000,80.934000,3.710000,0.074000,0.084000,0.065000,-0.019000
United Arab Emirates,78.120000,77.442000,79.458000,2.016000,0.148000,0.151000,0.144000,-0.007000
Oman,78.078000,76.357000,80.534000,4.177000,0.217000,0.230000,0.191000,-0.039000
Turkey,77.928000,74.984000,80.769000,5.785000,0.237000,0.260000,0.206000,-0.054000
Bahrain,77.419000,76.559000,78.557000,1.998000,0.127000,0.123000,0.134000,0.011000
Europe & Central Asia,77.390450,74.346494,80.629805,6.283311,-0.768678,-0.787938,-0.742027,0.045911
Thailand,77.344000,73.677000,81.062000,7.385000,0.194000,0.217000,0.162000,-0.055000
Sri Lanka,77.144000,73.779000,80.399000,6.620000,0.166000,0.183000,0.138000,-0.045000
China,77.097000,74.953000,79.411000,4.458000,0.185000,0.192000,0.167000,-0.025000
Iran,76.870000,75.775000,78.088000,2.313000,0.193000,0.182000,0.203000,0.021000
East Asia & Pacific,76.443450,73.990590,79.054221,5.063631,0.177842,0.179335,0.169038,-0.010297
Malaysia,76.306000,74.381000,78.458000,4.077000,0.150000,0.147000,0.141000,-0.006000
Brunei,75.998000,74.859000,77.256000,2.397000,0.138000,0.131000,0.150000,0.019000
Kuwait,75.586000,74.851000,76.706000,1.855000,0.097000,0.091000,0.126000,0.035000
Vietnam,75.493000,71.407000,79.609000,8.202000,0.093000,0.106000,0.086000,-0.020000
Saudi Arabia,75.280000,74.079000,76.919000,2.840000,0.147000,0.144000,0.160000,0.016000
Armenia,75.224000,71.453000,78.652000,7.199000,0.137000,0.126000,0.136000,0.010000
Jordan,74.655000,72.956000,76.445000,3.489000,0.129000,0.117000,0.139000,0.022000
Middle East & North Africa,74.447734,72.813497,76.247440,3.433942,0.176860,0.180291,0.169070,-0.011220
Georgia,73.919000,69.508000,78.273000,8.765000,0.152000,0.159000,0.133000,-0.026000
Syria,73.651000,69.387000,78.419000,9.032000,0.954000,1.446000,0.316000,-1.130000
Azerbaijan,73.123000,70.630000,75.574000,4.944000,0.118000,0.119000,0.119000,0.000000
Bangladesh,72.868000,71.130000,74.893000,3.763000,0.277000,0.253000,0.298000,0.045000
World,72.747303,70.572878,75.062444,4.489566,-0.015364,-0.025228,-0.005665,0.019563
North Korea,72.453000,68.798000,75.932000,7.134000,0.179000,0.183000,0.188000,0.005000
Egypt,72.150000,69.883000,74.530000,4.647000,0.160000,0.141000,0.180000,0.039000
Bhutan,72.080000,71.673000,72.524000,0.851000,0.303000,0.268000,0.348000,0.080000
Indonesia,71.908000,69.750000,74.173000,4.423000,0.192000,0.178000,0.206000,0.028000
Uzbekistan,71.848000,69.697000,73.968000,4.271000,0.123000,0.105000,0.139000,0.034000
Kyrgyzstan,71.800000,67.800000,76.000000,8.200000,0.200000,0.200000,0.200000,0.000000
Kazakhstan,71.370000,67.090000,75.530000,8.440000,-1.810000,-1.730000,-1.770000,-0.040000
Philippines,71.360000,67.390000,75.623000,8.233000,0.129000,0.127000,0.118000,-0.009000
Russia,71.338780,66.490000,76.430000,9.940000,-1.745122,-1.750000,-1.740000,0.010000
Tajikistan,71.301000,69.121000,73.599000,4.478000,0.204000,0.186000,0.210000,0.024000
Nepal,71.067000,69.521000,72.510000,2.989000,0.289000,0.262000,0.302000,0.040000
Iraq,70.748000,68.691000,72.815000,4.124000,0.144000,0.126000,0.163000,0.037000
Mongolia,70.056000,65.973000,74.326000,8.353000,0.186000,0.174000,0.184000,0.010000
Cambodia,70.054000,67.748000,72.163000,4.415000,0.231000,0.210000,0.254000,0.044000
India,69.887000,68.678000,71.202000,2.524000,0.231000,0.214000,0.252000,0.038000
South Asia,69.867847,68.597906,71.258224,2.660318,0.224229,0.206687,0.244234,0.037547
Timor-Leste,69.712000,67.692000,71.869000,4.177000,0.217000,0.200000,0.234000,0.034000
Turkmenistan,68.313000,64.813000,71.852000,7.039000,0.122000,0.108000,0.135000,0.027000
Laos,68.219000,66.425000,70.061000,3.636000,0.296000,0.283000,0.315000,0.032000
Pakistan,67.428000,66.471000,68.464000,1.993000,0.155000,0.134000,0.177000,0.043000
Myanmar,67.363000,64.276000,70.342000,6.066000,0.229000,0.230000,0.223000,-0.007000
Yemen,66.181000,64.491000,67.885000,3.394000,0.056000,0.048000,0.059000,0.011000
Afghanistan,65.173000,63.708000,66.744000,3.036000,0.340000,0.326000,0.356000,0.030000

In [15]:
table_code_Asia = create_table(df_Asia)
output_table_code(table_code_Asia, 'Table code WBG -2020 -Asia -en.txt', destination='file')

Data has written to file

In [16]:
table_code_Asia = create_table(df_Asia, lang='ru')
output_table_code(table_code_Asia, 'Table code WBG -2020 -Asia -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [17]:
dd_Europe = ['Albania', 'Armenia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus',
             'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy',
             'Kazakhstan', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Moldova', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway',
             'Poland', 'Portugal', 'Romania', 'Russia', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland',
             'Turkey', 'Ukraine', 'United Kingdom', 'Liechtenstein',
             'World', 'European Union', 'Central Europe and the Baltics']  # 'Europe & Central Asia'
# small countries: Andorra, Liechtenstein, Monaco, San Marino, Vatican City

df_Europe = df.loc[dd_Europe]   \
              .sort_values(by='total', ascending=False)
df_Europe

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Norway,83.209756,81.600000,84.900000,3.300000,0.251220,0.300000,0.200000,-1.000000e-01
Switzerland,83.100000,81.100000,85.200000,4.100000,-0.804878,-1.000000,-0.600000,4.000000e-01
Iceland,83.065854,81.700000,84.500000,2.800000,-0.097561,0.000000,-0.200000,-2.000000e-01
Malta,82.653659,80.800000,84.600000,3.800000,-0.204878,-0.400000,0.000000,4.000000e-01
Sweden,82.407317,80.700000,84.200000,3.500000,-0.702439,-0.800000,-0.600000,2.000000e-01
Italy,82.343902,80.100000,84.700000,4.600000,-1.153659,-1.300000,-1.000000,3.000000e-01
Spain,82.334146,79.700000,85.100000,5.400000,-1.497561,-1.400000,-1.600000,-2.000000e-01
Ireland,82.204878,80.400000,84.100000,3.700000,-0.497561,-0.400000,-0.600000,-2.000000e-01
France,82.175610,79.200000,85.300000,6.100000,-0.651220,-0.700000,-0.600000,1.000000e-01
Finland,82.131707,79.400000,85.000000,5.600000,0.148780,0.100000,0.200000,1.000000e-01
Liechtenstein,81.807317,80.100000,83.600000,3.500000,-2.353659,-2.500000,-2.200000,3.000000e-01
Luxembourg,81.741463,79.400000,84.200000,4.800000,-0.897561,-0.800000,-1.000000,-2.000000e-01
Denmark,81.551220,79.600000,83.600000,4.000000,0.100000,0.100000,0.100000,0.000000e+00
Netherlands,81.409756,79.800000,83.100000,3.300000,-0.702439,-0.800000,-0.600000,2.000000e-01
Austria,81.192683,78.900000,83.600000,4.700000,-0.702439,-0.800000,-0.600000,2.000000e-01
Cyprus,81.135000,79.103000,83.151000,4.048000,0.153000,0.182000,0.119000,-6.300000e-02
Greece,81.087805,78.600000,83.700000,5.100000,-0.551220,-0.600000,-0.500000,1.000000e-01
Portugal,80.975610,78.000000,84.100000,6.100000,-0.700000,-0.700000,-0.700000,0.000000e+00
Germany,80.941463,78.600000,83.400000,4.800000,-0.351220,-0.400000,-0.300000,1.000000e-01
United Kingdom,80.902439,79.000000,82.900000,3.900000,-0.302439,-0.400000,-0.200000,2.000000e-01
Belgium,80.795122,78.600000,83.100000,4.500000,-1.200000,-1.200000,-1.200000,0.000000e+00
Slovenia,80.531707,77.800000,83.400000,5.600000,-0.997561,-0.900000,-1.100000,-2.000000e-01
European Union,80.463702,77.752226,83.324359,5.572133,-0.849568,-0.911698,-0.783282,1.284166e-01
Albania,78.686000,77.163000,80.256000,3.093000,0.113000,0.161000,0.055000,-1.060000e-01
Estonia,78.346341,74.200000,82.700000,8.500000,-0.300000,-0.300000,-0.300000,0.000000e+00
Czechia,78.226829,75.300000,81.300000,6.000000,-1.002439,-1.100000,-0.900000,2.000000e-01
Turkey,77.928000,74.984000,80.769000,5.785000,0.237000,0.260000,0.206000,-5.400000e-02
Croatia,77.724390,74.700000,80.900000,6.200000,-0.700000,-0.700000,-0.700000,1.421085e-14
Bosnia and Herzegovina,77.545000,75.048000,79.991000,4.943000,0.144000,0.155000,0.134000,-2.100000e-02
Slovakia,76.865854,73.500000,80.400000,6.900000,-0.800000,-0.800000,-0.800000,0.000000e+00
Poland,76.600000,72.600000,80.800000,8.200000,-1.304878,-1.500000,-1.100000,4.000000e-01
Central Europe and the Baltics,76.144169,72.444176,80.036609,7.592433,-1.122675,-1.258176,-0.980493,2.776830e-01
Montenegro,75.931707,73.200000,78.800000,5.600000,-0.751220,-0.800000,-0.700000,1.000000e-01
North Macedonia,75.693171,73.620000,77.870000,4.250000,-0.909268,-1.080000,-0.730000,3.500000e-01
Hungary,75.617073,72.300000,79.100000,6.800000,-0.702439,-0.800000,-0.600000,2.000000e-01
Latvia,75.387805,70.900000,80.100000,9.200000,0.000000,0.000000,0.000000,0.000000e+00
Armenia,75.224000,71.453000,78.652000,7.199000,0.137000,0.126000,0.136000,1.000000e-02
Lithuania,74.929268,70.100000,80.000000,9.900000,-1.353659,-1.500000,-1.200000,3.000000e-01
Romania,74.353659,70.500000,78.400000,7.900000,-1.253659,-1.400000,-1.100000,3.000000e-01
Serbia,74.229268,71.400000,77.200000,5.800000,-1.707317,-2.000000,-1.400000,6.000000e-01
Belarus,74.226829,69.300000,79.400000,10.100000,0.000000,0.000000,0.000000,0.000000e+00
Georgia,73.919000,69.508000,78.273000,8.765000,0.152000,0.159000,0.133000,-2.600000e-02
Bulgaria,73.607317,69.900000,77.500000,7.600000,-1.504878,-1.700000,-1.300000,4.000000e-01
Azerbaijan,73.123000,70.630000,75.574000,4.944000,0.118000,0.119000,0.119000,0.000000e+00
World,72.747303,70.572878,75.062444,4.489566,-0.015364,-0.025228,-0.005665,1.956331e-02
Moldova,72.006000,67.728000,76.253000,8.525000,0.105000,0.104000,0.096000,-8.000000e-03
Kazakhstan,71.370000,67.090000,75.530000,8.440000,-1.810000,-1.730000,-1.770000,-4.000000e-02
Russia,71.338780,66.490000,76.430000,9.940000,-1.745122,-1.750000,-1.740000,1.000000e-02
Ukraine,71.185122,66.390000,76.220000,9.830000,-0.642195,-0.530000,-0.760000,-2.300000e-01

In [18]:
table_code_Europe = create_table(df_Europe)
output_table_code(table_code_Europe, 'Table code WBG -2020 -Europe -en.txt', destination='file')

Data has written to file

In [19]:
table_code_Europe = create_table(df_Europe, lang='ru')
output_table_code(table_code_Europe, 'Table code WBG -2020 -Europe -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [20]:
dd_Africa = ['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cameroon', 'Cabo Verde',
             "Cote d'Ivoire", 'Central African Republic', 'Chad', 'Comoros', 'Congo, Democratic Republic of',
             'Congo, Republic of', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini',
             'Ethiopia', 'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya',
             'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius',
             'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Sao Tome and Principe',
             'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan',
             'Tanzania', 'Togo', 'Tunisia', 'Uganda', 'Zambia', 'Zimbabwe',
             'World', 'Middle East & North Africa', 'Africa Eastern and Southern', 'Sub-Saharan Africa', 'Africa Western and Central']

df_Africa = df.loc[dd_Africa]   \
              .sort_values(by='total', ascending=False)
df_Africa

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Seychelles,77.236585,72.700000,82.000000,9.300000,3.190244,2.800000,3.600000,0.800000
Algeria,77.063000,75.857000,78.321000,2.464000,0.183000,0.181000,0.188000,0.007000
Morocco,76.901000,75.646000,78.118000,2.472000,0.221000,0.223000,0.223000,0.000000
Tunisia,76.891000,74.883000,78.903000,4.020000,0.192000,0.195000,0.182000,-0.013000
Middle East & North Africa,74.447734,72.813497,76.247440,3.433942,0.176860,0.180291,0.169070,-0.011220
Mauritius,74.177073,70.860000,77.660000,6.800000,-0.058780,-0.210000,0.100000,0.310000
Cabo Verde,73.166000,69.721000,76.384000,6.663000,0.185000,0.195000,0.187000,-0.008000
Libya,73.082000,70.271000,76.105000,5.834000,0.169000,0.174000,0.154000,-0.020000
World,72.747303,70.572878,75.062444,4.489566,-0.015364,-0.025228,-0.005665,0.019563
Egypt,72.150000,69.883000,74.530000,4.647000,0.160000,0.141000,0.180000,0.039000
Sao Tome and Principe,70.583000,68.159000,73.029000,4.870000,0.198000,0.179000,0.215000,0.036000
Botswana,69.793000,66.665000,72.604000,5.939000,0.201000,0.180000,0.218000,0.038000
Rwanda,69.329000,67.108000,71.456000,4.348000,0.305000,0.287000,0.324000,0.037000
Senegal,68.213000,66.014000,70.203000,4.189000,0.272000,0.257000,0.285000,0.028000
Djibouti,67.490000,65.467000,69.766000,4.299000,0.378000,0.351000,0.409000,0.058000
Madagascar,67.390000,65.749000,69.051000,3.302000,0.349000,0.332000,0.369000,0.037000
Kenya,66.991000,64.595000,69.352000,4.757000,0.292000,0.282000,0.303000,0.021000
Ethiopia,66.953000,65.036000,68.905000,3.869000,0.356000,0.342000,0.369000,0.027000
Gabon,66.690000,64.577000,68.931000,4.354000,0.223000,0.195000,0.262000,0.067000
Eritrea,66.679000,64.496000,68.924000,4.428000,0.358000,0.343000,0.369000,0.026000
Tanzania,65.815000,64.009000,67.587000,3.578000,0.359000,0.366000,0.354000,-0.012000
Sudan,65.530000,63.665000,67.429000,3.764000,0.219000,0.198000,0.242000,0.044000
Mauritania,65.129000,63.500000,66.731000,3.231000,0.204000,0.195000,0.216000,0.021000
"Congo, Republic of",64.804000,63.291000,66.287000,2.996000,0.234000,0.209000,0.264000,0.055000
Malawi,64.694000,61.524000,67.850000,6.326000,0.431000,0.423000,0.437000,0.014000
Comoros,64.525000,62.775000,66.341000,3.566000,0.204000,0.188000,0.220000,0.032000
Liberia,64.423000,63.020000,65.831000,2.811000,0.319000,0.305000,0.334000,0.029000
South Africa,64.379000,60.966000,67.930000,6.964000,0.248000,0.240000,0.251000,0.011000
Ghana,64.347000,63.238000,65.477000,2.239000,0.273000,0.247000,0.300000,0.053000
Africa Eastern and Southern,64.325702,62.121491,66.534628,4.413137,0.320490,0.308306,0.332512,0.024206
Zambia,64.194000,61.125000,67.236000,6.111000,0.308000,0.277000,0.345000,0.068000
Namibia,64.045000,61.016000,66.853000,5.837000,0.337000,0.331000,0.337000,0.006000
Uganda,63.713000,61.317000,66.001000,4.684000,0.345000,0.317000,0.379000,0.062000
Niger,62.792000,61.636000,64.010000,2.374000,0.372000,0.355000,0.389000,0.034000
Gambia,62.383000,60.969000,63.827000,2.858000,0.333000,0.313000,0.346000,0.033000
Benin,62.077000,60.494000,63.646000,3.152000,0.306000,0.293000,0.322000,0.029000
Burkina Faso,61.981000,61.119000,62.724000,1.605000,0.404000,0.380000,0.430000,0.050000
Guinea,61.962000,61.180000,62.507000,1.327000,0.360000,0.325000,0.390000,0.065000
Sub-Saharan Africa,61.951109,60.169164,63.748177,3.579013,0.323657,0.309816,0.338031,0.028216
Burundi,61.916000,60.086000,63.721000,3.635000,0.332000,0.322000,0.344000,0.022000
Zimbabwe,61.738000,60.037000,63.164000,3.127000,0.248000,0.239000,0.265000,0.026000
Angola,61.487000,58.744000,64.383000,5.639000,0.340000,0.328000,0.344000,0.016000
Mozambique,61.387000,58.302000,64.211000,5.909000,0.533000,0.520000,0.540000,0.020000
Togo,61.340000,60.429000,62.239000,1.810000,0.298000,0.277000,0.321000,0.044000
"Congo, Democratic Republic of",60.971000,59.420000,62.540000,3.120000,0.290000,0.273000,0.307000,0.034000
Eswatini,60.721000,56.515000,65.411000,8.896000,0.527000,0.508000,0.566000,0.058000
Mali,59.692000,58.894000,60.492000,1.598000,0.386000,0.365000,0.407000,0.042000
Cameroon,59.626000,58.354000,60.904000,2.550000,0.334000,0.325000,0.343000,0.018000
Equatorial Guinea,59.057000,58.056000,60.250000,2.194000,0.322000,0.313000,0.332000,0.019000
Guinea-Bissau,58.634000,56.620000,60.524000,3.904000,0.312000,0.315000,0.311000,-0.004000
Africa Western and Central,58.445953,57.325886,59.579346,2.253460,0.330230,0.313723,0.348274,0.034550
Cote d'Ivoire,58.104000,56.897000,59.455000,2.558000,0.321000,0.304000,0.336000,0.032000
South Sudan,58.095000,56.593000,59.640000,3.047000,0.249000,0.242000,0.257000,0.015000
Somalia,57.697000,56.011000,59.443000,3.432000,0.300000,0.286000,0.311000,0.025000
Sierra Leone,55.066000,54.213000,55.875000,1.662000,0.370000,0.360000,0.380000,0.020000
Nigeria,55.018000,54.104000,55.969000,1.865000,0.331000,0.315000,0.350000,0.035000
Lesotho,54.836000,51.703000,58.087000,6.384000,0.505000,0.502000,0.507000,0.005000
Chad,54.505000,53.093000,55.945000,2.852000,0.266000,0.258000,0.276000,0.018000
Central African Republic,53.679000,51.454000,55.932000,4.478000,0.396000,0.373000,0.418000,0.045000

In [21]:
table_code_Africa = create_table(df_Africa)
output_table_code(table_code_Africa, 'Table code WBG -2020 -Africa -en.txt', destination='file')

Data has written to file

In [22]:
table_code_Africa = create_table(df_Africa, lang='ru')
output_table_code(table_code_Africa, 'Table code WBG -2020 -Africa -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [23]:
dd_CIS = ['Armenia', 'Azerbaijan', 'Belarus', 'Kazakhstan', 'Kyrgyzstan', 'Moldova',
          'Russia', 'Tajikistan', 'Uzbekistan', 'Turkmenistan', 'Ukraine']

df_CIS = df.loc[dd_CIS]   \
           .sort_values(by='total', ascending=False)
df_CIS

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Armenia,75.224000,71.453,78.652,7.199,0.137000,0.126,0.136,0.010
Belarus,74.226829,69.300,79.400,10.100,0.000000,0.000,0.000,0.000
Azerbaijan,73.123000,70.630,75.574,4.944,0.118000,0.119,0.119,0.000
Moldova,72.006000,67.728,76.253,8.525,0.105000,0.104,0.096,-0.008
Uzbekistan,71.848000,69.697,73.968,4.271,0.123000,0.105,0.139,0.034
Kyrgyzstan,71.800000,67.800,76.000,8.200,0.200000,0.200,0.200,0.000
Kazakhstan,71.370000,67.090,75.530,8.440,-1.810000,-1.730,-1.770,-0.040
Russia,71.338780,66.490,76.430,9.940,-1.745122,-1.750,-1.740,0.010
Tajikistan,71.301000,69.121,73.599,4.478,0.204000,0.186,0.210,0.024
Ukraine,71.185122,66.390,76.220,9.830,-0.642195,-0.530,-0.760,-0.230
Turkmenistan,68.313000,64.813,71.852,7.039,0.122000,0.108,0.135,0.027

In [24]:
# table_code_CIS = create_table(df_CIS)
# output_table_code(table_code_CIS, 'Table code WBG -2020 -CIS -en.txt', destination='file')

In [25]:
table_code_CIS = create_table(df_CIS, lang='ru')
output_table_code(table_code_CIS, 'Table code WBG -2020 -CIS -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [26]:
ls_regions = [
    'European Union', 'Central Europe and the Baltics',
    'Europe & Central Asia',
    'South Asia',
    'East Asia & Pacific',
    'Middle East & North Africa',
    'Africa Eastern and Southern', 'Sub-Saharan Africa', 'Africa Western and Central',
    'North America', 'Latin America & Caribbean',
    'Arab World'
]

In [27]:
df_all_countries = df.drop(ls_regions)

In [28]:
table_code_all_countries = create_table(df_all_countries)
output_table_code(table_code_all_countries, 'Table code WBG -2020 -all_countries -en.txt', destination='file')

Data has written to file

In [29]:
table_code_all_countries = create_table(df_all_countries, lang='ru')
output_table_code(table_code_all_countries, 'Table code WBG -2020 -all_countries -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [30]:
# create code for placing info in Wikipedia
def create_table_for_regions(df, lang='en'):

    if lang=='ru':
        file_header='wbg_stats_header_2020_ru.txt'
        ptn_1 = 'флагификация'
        ptn_2 = 'флаг'
        prettify_name = {
            'European Union': '[[Европейский союз]]',
            'Central Europe and the Baltics': '[[Центральная Европа]] и [[Прибалтика]]',
            'Europe & Central Asia': '[[Европа]] и [[Центральная Азия]]',
            'South Asia': '[[Южная Азия]]',
            'East Asia & Pacific': '[[Восточная Азия]] и [[Австралия и Океания|Океания]]',
            'Middle East & North Africa': '[[Страны MENA|Ближний Восток и Северная Африка]]',
            'Africa Eastern and Southern': '[[Восточная Африка|Восточная]] и [[Южная Африка|Южная]] Африка',
            'Sub-Saharan Africa': '[[Чёрная Африка|Африка к югу от Сахары]]',
            'Africa Western and Central': '[[Западная Африка|Западная]] и [[Центральная Африка|Центральная]] Африка',
            'North America': '[[Северная Америка]]',
            'Latin America & Caribbean': '[[Латинская Америка]] и [[Антильские острова|Карибы]]',
            'Arab World': 'Арабский мир',
            'World': 'Мир'
        }
    else:
        file_header='wbg_stats_header_2020_en.txt'
        ptn_1 = 'flaglist'
        ptn_2 = 'flagicon'
        prettify_name = {
            'European Union': '[[European Union]]',
            'Central Europe and the Baltics': '[[Central Europe]] & the [[Baltic states|Baltics]]',
            'Europe & Central Asia': '[[Europe]] & [[Central Asia]]',
            'South Asia': '[[South Asia]]',
            'East Asia & Pacific': '[[Asia-Pacific|East Asia & Pacific]]',
            'Middle East & North Africa': '[[MENA|Middle East & North Africa]]',
            'Africa Eastern and Southern': 'Africa [[East Africa|Eastern]] & [[Southern Africa|Southern]]',
            'Sub-Saharan Africa': '[[Sub-Saharan Africa]]',
            'Africa Western and Central': 'Africa [[West Africa|Western]] & [[Central Africa|Central]]',
            'North America': '[[North America]]',
            'Latin America & Caribbean': '[[Latin America and the Caribbean|Latin America & Caribbean]]'
        }
        
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st = fh.read()
        
    st = st[:-1]
        
    for i in range(len(df)):
        ser = df.iloc[i]
        if ser.name in ['World']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|align=center| \'\'\'{prettify_name.get(ser.name, ser.name)}\'\'\' ' + \
                  f'||style="text-align:center; background:#e0ffd8;"| \'\'\'{ser.total:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| \'\'\'{ser.male:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#fee7f6;"| \'\'\'{ser.female:0.2f}\'\'\' ' + \
                  f'||style="text-align:center;"| \'\'\'{ser.gender_gap:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#e0ffd8; border-left-width:2px;"| \'\'\'{ser.Δ_2019_total:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| \'\'\'{ser.Δ_2019_male:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#fee7f6;"| \'\'\'{ser.Δ_2019_female:0.2f}\'\'\' ' + \
                  f'||style="text-align:center;"| \'\'\'{ser.Δ_2019_gender_gap:0.2f}\'\'\''
        else:
            st += '\n' + '|-\n' + \
                  f'|align=left|{prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="text-align:center; background:#e0ffd8;"| {ser.total:0.2f} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {ser.male:0.2f} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {ser.female:0.2f} ' + \
                  f'||style="text-align:center;"| {ser.gender_gap:0.2f} ' + \
                  f'||style="text-align:center; background:#e0ffd8; border-left-width:2px;"| {ser.Δ_2019_total:0.2f} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {ser.Δ_2019_male:0.2f} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {ser.Δ_2019_female:0.2f} ' + \
                  f'||style="text-align:center;"| {ser.Δ_2019_gender_gap:0.2f}'
    st += '\n|}'
    return st

In [31]:
df_regions = df.loc[ls_regions + ['World']]   \
               .sort_values(by='total', ascending=False)
df_regions

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
European Union,80.463702,77.752226,83.324359,5.572133,-0.849568,-0.911698,-0.783282,0.128417
North America,77.741163,75.036702,80.579831,5.543129,-1.382202,-1.644449,-1.107172,0.537277
Europe & Central Asia,77.390450,74.346494,80.629805,6.283311,-0.768678,-0.787938,-0.742027,0.045911
East Asia & Pacific,76.443450,73.990590,79.054221,5.063631,0.177842,0.179335,0.169038,-0.010297
Central Europe and the Baltics,76.144169,72.444176,80.036609,7.592433,-1.122675,-1.258176,-0.980493,0.277683
Latin America & Caribbean,75.762428,72.639440,78.901580,6.262140,0.160933,0.178640,0.141231,-0.037409
Middle East & North Africa,74.447734,72.813497,76.247440,3.433942,0.176860,0.180291,0.169070,-0.011220
World,72.747303,70.572878,75.062444,4.489566,-0.015364,-0.025228,-0.005665,0.019563
Arab World,72.170760,70.497197,74.000521,3.503324,0.181051,0.189014,0.168207,-0.020807
South Asia,69.867847,68.597906,71.258224,2.660318,0.224229,0.206687,0.244234,0.037547
Africa Eastern and Southern,64.325702,62.121491,66.534628,4.413137,0.320490,0.308306,0.332512,0.024206
Sub-Saharan Africa,61.951109,60.169164,63.748177,3.579013,0.323657,0.309816,0.338031,0.028216
Africa Western and Central,58.445953,57.325886,59.579346,2.253460,0.330230,0.313723,0.348274,0.034550

In [32]:
table_code_regions = create_table_for_regions(df_regions)

output_table_code(table_code_regions, 'Table code WBG -2020 -z_regions -en.txt', destination='file')

Data has written to file

In [33]:
table_code_regions = create_table_for_regions(df_regions, lang='ru')

output_table_code(table_code_regions, 'Table code WBG -2020 -z_regions -ru.txt', destination='file')

Data has written to file