The World Band > [Life expectancy at birth, total](https://data.worldbank.org/indicator/SP.DYN.LE00.IN)<br />
The World Band > [Life expectancy at birth, male](https://data.worldbank.org/indicator/SP.DYN.LE00.MA.IN)<br />
The World Band > [Life expectancy at birth, female](https://data.worldbank.org/indicator/SP.DYN.LE00.FE.IN)<br />
[World Development Indicators > Life expectancy at birth](https://databank.worldbank.org/reports.aspx?source=2&series=SP.DYN.LE00.IN&country=) *(databank.worldbank.org)*<br />
[OECD stat](https://stats.oecd.org/index.aspx?queryid=30114)

"[Список стран по ожидаемой продолжительности жизни](https://ru.wikipedia.org/wiki/Список_стран_по_ожидаемой_продолжительности_жизни)"<br />
"[Продолжительность жизни в субъектах Российской Федерации](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_субъектах_Российской_Федерации)"<br />
[Таблица подбора цветов](http://mal-bioit.ru/survey-web-colors)<br />
[Список государств и зависимых территорий по населению](https://ru.wikipedia.org/wiki/Список_государств_и_зависимых_территорий_по_населению)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math
import re

In [2]:
pd.options.display.max_rows = 300

DESTINATION_OUTPUT = ''  # to where table code should be placed: 'file', 'here' or just print 'Done'

In [3]:
def output_table_code(st, file_name='', destination=''):
    if not destination:
        destination = DESTINATION_OUTPUT
        
    if destination == 'file':
        with open('output/'+file_name, 'w', encoding="utf-8") as fh:
            fh.write(st)
        print('Data has written to file')
    elif destination == 'here':
        print(st)
    else:
        print('done')

In [4]:
# create code for placing info in Wikipedia
def create_table(df, lang='en'):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"
    
    if lang=='ru':
        file_header='wbg_stats_header_2020_ru.txt'
        ptn_1 = 'флагификация'
        ptn_2 = 'флаг'
        prettify_name = {
            'European Union': '[[Европейский союз]]',
            'Central Europe and the Baltics': '[[Центральная Европа]] и [[Прибалтика]]',
            'Europe & Central Asia': '[[Европа]] и [[Центральная Азия]]',
            'South Asia': '[[Южная Азия]]',
            'East Asia & Pacific': '[[Восточная Азия]] и [[Австралия и Океания|Океания]]',
            'Middle East & North Africa': '[[Страны MENA|Ближний Восток и Северная Африка]]',
            'Africa Eastern and Southern': '[[Восточная Африка|Восточная]] и [[Южная Африка|Южная]] Африка',
            'Sub-Saharan Africa': '[[Чёрная Африка|Африка к югу от Сахары]]',
            'Africa Western and Central': '[[Западная Африка|Западная]] и [[Центральная Африка|Центральная]] Африка',
            'North America': '[[Северная Америка]]',
            'Latin America & Caribbean': '[[Латинская Америка]] и [[Антильские острова|Карибы]]',
            'Arab World': 'Арабский мир',
            'World': 'Мир',
            'Caribbean small states': '[[Список стран Карибского бассейна|Малые страны Карибского бассейна]]',
            'Pacific island small states': 'Малые страны Тихого океана',
            'Small states': 'Малые страны',
            'Other small states': 'Другие малые страны'
        }
    else:
        file_header='wbg_stats_header_2020_en.txt'
        ptn_1 = 'flaglist'
        ptn_2 = 'flagicon'
        prettify_name = {
            'European Union': '[[European Union]]',
            'Central Europe and the Baltics': '[[Central Europe]] & the [[Baltic states|Baltics]]',
            'Europe & Central Asia': '[[Europe]] & [[Central Asia]]',
            'South Asia': '[[South Asia]]',
            'East Asia & Pacific': '[[Asia-Pacific|East Asia & Pacific]]',
            'Middle East & North Africa': '[[MENA|Middle East & North Africa]]',
            'Africa Eastern and Southern': 'Africa [[East Africa|Eastern]] & [[Southern Africa|Southern]]',
            'Sub-Saharan Africa': '[[Sub-Saharan Africa]]',
            'Africa Western and Central': 'Africa [[West Africa|Western]] & [[Central Africa|Central]]',
            'North America': '[[North America]]',
            'Latin America & Caribbean': '[[Latin America and the Caribbean|Latin America & Caribbean]]'
        }
        
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st = fh.read()
        
    st = st.strip()
        
    for i in range(len(df)):
        ser = df.iloc[i]
        if ser.name in ['World',
                        'European Union', 'Central Europe and the Baltics',
                        'Europe & Central Asia',
                        'South Asia',
                        'East Asia & Pacific',
                        'Middle East & North Africa',
                        'Africa Eastern and Southern', 'Sub-Saharan Africa', 'Africa Western and Central',
                        'North America', 'Latin America & Caribbean']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|align=center| \'\'\'{prettify_name.get(ser.name, ser.name)}\'\'\' ' + \
                  f'||style="text-align:center; background:#e0ffd8;"| \'\'\'{if_value(ser.total, 2)}\'\'\' ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| \'\'\'{if_value(ser.male, 2)}\'\'\' ' + \
                  f'||style="text-align:center; background:#fee7f6;"| \'\'\'{if_value(ser.female, 2)}\'\'\' ' + \
                  f'||style="text-align:center;"| \'\'\'{if_value(ser.gender_gap, 2)}\'\'\' ' + \
                  f'||style="text-align:center; background:#e0ffd8; border-left-width:2px;"| \'\'\'{if_value(ser.Δ_2019_total, 2)}\'\'\' ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| \'\'\'{if_value(ser.Δ_2019_male, 2)}\'\'\' ' + \
                  f'||style="text-align:center; background:#fee7f6;"| \'\'\'{if_value(ser.Δ_2019_female, 2)}\'\'\' ' + \
                  f'||style="text-align:center;"| \'\'\'{if_value(ser.Δ_2019_gender_gap, 2)}\'\'\''
        elif ser.name in ['Caribbean small states',
                          'Pacific island small states',
                          'Small states',
                          'Other small states']:
            st += '\n' + '|-\n' + \
                  f'|style="text-align:left; padding-left: 35px;"|{prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="text-align:center; background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {if_value(ser.male, 2)} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {if_value(ser.female, 2)} ' + \
                  f'||style="text-align:center;"| {if_value(ser.gender_gap, 2)} ' + \
                  f'||style="text-align:center; background:#e0ffd8; border-left-width:2px;"| {if_value(ser.Δ_2019_total, 2)} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {if_value(ser.Δ_2019_male, 2)} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {if_value(ser.Δ_2019_female, 2)} ' + \
                  f'||style="text-align:center;"| {if_value(ser.Δ_2019_gender_gap, 2)}'
        else:
            st += '\n' + '|-\n' + \
                  f'|align=left|{{{{{ptn_1}|{ser.name}}}}} ' + \
                  f'||style="text-align:center; background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {if_value(ser.male, 2)} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {if_value(ser.female, 2)} ' + \
                  f'||style="text-align:center;"| {if_value(ser.gender_gap, 2)} ' + \
                  f'||style="text-align:center; background:#e0ffd8; border-left-width:2px;"| {if_value(ser.Δ_2019_total, 2)} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {if_value(ser.Δ_2019_male, 2)} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {if_value(ser.Δ_2019_female, 2)} ' + \
                  f'||style="text-align:center;"| {if_value(ser.Δ_2019_gender_gap, 2)}'
    st += '\n|}'
    
    if lang == 'ru':
        st = re.sub('(?<=\d)\.(?=\d)', ',', st)  # replace . to comma, if this . is between two digits
    
    return st

In [5]:
def extract_data_for_year(df, year='2019'):
    ls_dropping = [
        'Hong Kong SAR, China',     # administrative region of China, population 7,291,000
        'Macao SAR, China',         # administrative region of China, population 682,000
        'Kosovo',                   # partially recognised state, population 1,806,000
        # 'West Bank and Gaza',        # Palestine, partially recognised state, population 5,227,000
        # 'New Caledonia',             # French Overseas Territory in Oceania, population 271,000
        # 'Channel Islands',           # archipelago in Europe, consisting of two Crown Dependencies, population 172,000
        # 'Curacao',                   #  constituent country of the Netherlands in S.America, population 149,000, little info about LE
        # 'Virgin Islands (U.S.)',     # unincorporated and organized territory of USA, population 87,000
        # 'Isle of Man',               # self-governing Crown Dependency, Europe, population 84,000
        # 'Dominica',                  # micro-state in N.America, population 72,400
        # 'Marshall Islands',          # micro-state in Oceania, population 62,000
        # 'Faroe Islands',             # autonomous territory of Denmark in Europe, population 54,000
        # 'St. Kitts and Nevis',       # micro-state in N.America, population 47,600
        # 'Turks and Caicos Islands',  # British Overseas Territory in N.America, population 44,000
        # 'Sint Maarten (Dutch part)', # constituent country of the Netherlands in N.America, population 41,500
        # 'Gibraltar',                 # British Overseas Territory in Europe, population 34,000
        # 'St. Martin (French part)',  # French Overseas Territory in N.America, population 32,500
        # 'British Virgin Islands',    # British Overseas Territory in N.America, population 30,000
        # 'Palau',           #  mini-state in Oceania, population 22,000, little info about LE
        # 'Tuvalu',                    # island micro-state in Oceania, population 12,000
        # 'Nauru'                      # micro-state in Oceania, population 11,000
        'Euro area',
        'IBRD only',
        'IDA & IBRD total',
        'IDA total',
        'IDA blend',
        'IDA only',
        'OECD members',
        'Small states',
        'Other small states',
        'Europe & Central Asia (excluding high income)',
        'East Asia & Pacific (excluding high income)',
        'Latin America & Caribbean (excluding high income)',
        'Middle East & North Africa (excluding high income)',
        'Sub-Saharan Africa (excluding high income)',
        'East Asia & Pacific (IDA & IBRD countries)',
        'Europe & Central Asia (IDA & IBRD countries)',
        'Middle East & North Africa (IDA & IBRD countries)',
        'Sub-Saharan Africa (IDA & IBRD countries)',           
        'Latin America & the Caribbean (IDA & IBRD countries)',
        'South Asia (IDA & IBRD)',
        'Heavily indebted poor countries (HIPC)',
        'Fragile and conflict affected situations',
        'Least developed countries: UN classification',
        'Early-demographic dividend',
        'Late-demographic dividend',
        'Pre-demographic dividend',
        'Post-demographic dividend',
        'Low income',
        'Lower middle income',
        'Low & middle income',
        'Middle income',
        'Upper middle income',
        'High income'
    ]
    
    ser = df.drop(ls_dropping) \
            [str(year)] \
            .dropna() \
            .rename(index = {'United States':'USA',
                             'Russian Federation': 'Russia',
                             'Korea, Rep.': 'South Korea',
                             'Egypt, Arab Rep.': 'Egypt',
                             'Congo, Dem. Rep.': 'DR Congo',   #'Congo, Democratic Republic of',
                             'Congo, Rep.': 'Congo, Rep.', #'Republic of the Congo', #'Congo Republic',  #'Congo, Republic of',
                             'Yemen, Rep.': 'Yemen',
                             'Micronesia, Fed. Sts.': 'Micronesia',
                             'Gambia, The': 'Gambia',
                             'Iran, Islamic Rep.': 'Iran',
                             "Korea, Dem. People's Rep.": 'North Korea',
                             'Syrian Arab Republic': 'Syria',
                             'Venezuela, RB': 'Venezuela',
                             'Kyrgyz Republic': 'Kyrgyzstan',
                             'Lao PDR': 'Laos',
                             'Czech Republic': 'Czechia',
                             'Slovak Republic': 'Slovakia',
                             'Bahamas, The': 'Bahamas',
                             'Brunei Darussalam': 'Brunei',
                             'Turkiye': 'Turkey',
                             'West Bank and Gaza': 'Palestine',
                             'Sint Maarten (Dutch part)': 'Sint Maarten',
                             'St. Martin (French part)': 'Collectivity of Saint Martin'
                            })
    
    return ser

In [6]:
df = pd.read_csv('data/World_Bank_Group-total.csv', skiprows=4, index_col=0)

ser_2020_total = extract_data_for_year(df, 2020)
ser_2020_total.name = '2020_total'

ser_2019_total = extract_data_for_year(df, 2019)
ser_2019_total.name = '2019_total'

del df

print(f"2020-total: {len(ser_2020_total)} records")
print(f"2019-total: {len(ser_2019_total)} records")

2020-total: 221 records
2019-total: 221 records

In [7]:
df = pd.read_csv('data/World_Bank_Group-male.csv', skiprows=4, index_col=0)

ser_2020_male = extract_data_for_year(df, 2020)
ser_2020_male.name = '2020_male'

ser_2019_male = extract_data_for_year(df, 2019)
ser_2019_male.name = '2019_male'

del df

print(f"2020-male: {len(ser_2020_male)} records")
print(f"2019-male: {len(ser_2019_male)} records")

2020-male: 221 records
2019-male: 221 records

In [8]:
df = pd.read_csv('data/World_Bank_Group-female.csv', skiprows=4, index_col=0)

ser_2020_female = extract_data_for_year(df, 2020)
ser_2020_female.name = '2020_female'

ser_2019_female = extract_data_for_year(df, 2019)
ser_2019_female.name = '2019_female'

del df

print(f"2020-female: {len(ser_2020_female)} records")
print(f"2019-female: {len(ser_2019_female)} records")

2020-female: 221 records
2019-female: 221 records

In [9]:
# concat series in DataFrame and rename columns in it
df = pd.concat([ser_2020_total, ser_2020_male, ser_2020_female, ser_2019_total, ser_2019_male, ser_2019_female],
               axis='columns', join='outer')

df.rename(columns={'2020_total': 'total',
                   '2020_male': 'male',
                   '2020_female': 'female'}, inplace=True)

df.index.name = ''

print(df.shape)
df.loc[['World', 'Russia']]

(221, 6)

           total       male    female  2019_total  2019_male  2019_female

World   72.24385  69.799734  74.85733   72.979716  70.623612    75.470008
Russia  71.33878  66.490000  76.43000   73.083902  68.240000    78.170000

In [10]:
# # calculate difference between some columns and insert result as new columns in dataframe
# df.insert(loc=3, column='gender_gap', value=df['female']-df['male'])


# df.insert(loc=7, column='2000→2014', value=df['2014_t']-df['2000_t'])
# df.insert(loc=8, column='2014→2019', value=df['2019_t']-df['2014_t'])
# df.insert(loc=9, column='2019→2020', value=df['2020_t']-df['2019_t'])
# df.insert(loc=11, column='2020→2021', value=df['total']-df['2020_t'])

# # sort DataFrame by total life expectancy
# df.sort_values(by=['total', 'male', 'female'], ascending=False, inplace=True)

In [11]:
# calculate difference between some columns and insert result as new columns in dataframe
df.insert(loc=3, column='gender_gap', value=df['female']-df['male'])
df['Δ_2019_total'] = df['total'] - df['2019_total']
df['Δ_2019_male'] = df['male'] - df['2019_male']
df['Δ_2019_female'] = df['female'] - df['2019_female']
df['Δ_2019_gender_gap'] = (df['female'] - df['male']) - (df['2019_female'] - df['2019_male'])

# drop redundant columns
df.drop(columns=['2019_total', '2019_male', '2019_female'], inplace=True)

# sort DataFrame by total life expectancy
df.sort_values(by=['total', 'male', 'female'], ascending=False, inplace=True)

print(df.shape)
df.loc[['World', 'Russia']]

(221, 8)

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
World,72.24385,69.799734,74.85733,5.057596,-0.735866,-0.823878,-0.612678,0.2112
Russia,71.33878,66.490000,76.43000,9.940000,-1.745122,-1.750000,-1.740000,0.0100

<br />
<br />
<br />

In [12]:
# ls_new = df.index.to_list()
# print(len(ls_new))

# ls_old = ['Japan', 'Singapore', 'South Korea', ...]

# print(len(ls_old))

In [13]:
# [country for country in ls_new if country not in ls_old]

In [14]:
# [country for country in ls_old if country not in ls_new]

<br />
<br />
<br />

In [15]:
dd_N_America = ['Antigua and Barbuda', 'Bahamas', 'Barbados', 'Belize', 'Canada', 'Costa Rica',
                'Cuba', 'Dominican Republic', 'El Salvador', 'Grenada', 'Guatemala',
                'Haiti', 'Honduras', 'Jamaica', 'Mexico', 'Nicaragua', 'Panama',
                'St. Lucia', 'St. Vincent and the Grenadines',
                'Trinidad and Tobago', 'USA',
                'World',                
                'Bermuda', 'Puerto Rico', 'Virgin Islands (U.S.)', 'British Virgin Islands', 'Turks and Caicos Islands',
                'Caribbean small states', 'Sint Maarten', 'Collectivity of Saint Martin', 'Dominica', 'St. Kitts and Nevis',
                'Aruba', 'Greenland']
# no values in the source: ['Dominica', 'St. Kitts and Nevis']

df_N_America = df.loc[dd_N_America]   \
                 .sort_values(by='total', ascending=False)
df_N_America

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Canada,81.670488,79.490000,83.960000,4.470000,-0.558293,-0.690000,-0.420000,0.270000
Bermuda,81.136000,77.885000,84.272000,6.387000,0.103000,0.094000,0.094000,0.000000
Collectivity of Saint Martin,80.149000,77.021000,83.423000,6.402000,0.166000,0.146000,0.163000,0.017000
Virgin Islands (U.S.),79.819512,76.600000,83.200000,6.600000,0.151220,0.200000,0.100000,-0.100000
Costa Rica,79.277000,76.751000,81.912000,5.161000,-0.150000,-0.251000,-0.041000,0.210000
Antigua and Barbuda,78.841000,76.061000,81.316000,5.255000,0.150000,0.152000,0.145000,-0.007000
Puerto Rico,78.041000,73.644000,82.588000,8.944000,-1.022000,-1.188000,-0.868000,0.320000
Cuba,77.567000,75.044000,80.225000,5.181000,-0.044000,-0.200000,0.150000,0.350000
Barbados,77.393000,75.418000,79.210000,3.792000,0.136000,0.188000,0.087000,-0.101000
USA,76.980488,74.200000,79.900000,5.700000,-1.807317,-2.100000,-1.500000,0.600000
Panama,76.657000,73.472000,80.034000,6.562000,-1.153000,-1.317000,-0.920000,0.397000
British Virgin Islands,75.849000,73.110000,78.763000,5.653000,-0.014000,-0.003000,-0.041000,-0.038000
Aruba,75.723000,72.828000,78.445000,5.617000,-0.525000,-0.458000,-0.565000,-0.107000
Turks and Caicos Islands,75.001000,72.198000,78.155000,5.957000,-0.325000,-0.402000,-0.216000,0.186000
Grenada,74.924000,72.208000,77.869000,5.661000,0.061000,0.079000,0.035000,-0.044000
Sint Maarten,74.584000,71.789000,77.883000,6.094000,-0.853000,-0.752000,-0.914000,-0.162000
Trinidad and Tobago,74.406000,70.983000,77.881000,6.898000,0.178000,0.155000,0.184000,0.029000
Dominica,73.649000,70.433000,77.260000,6.827000,0.090000,0.078000,0.055000,-0.023000
St. Lucia,73.416000,70.042000,77.055000,7.013000,-0.029000,-0.058000,-0.003000,0.055000
Dominican Republic,72.889000,69.364000,76.914000,7.550000,-0.688000,-1.107000,-0.051000,1.056000
Belize,72.854000,69.564000,76.626000,7.062000,-1.077000,-1.498000,-0.621000,0.877000
Bahamas,72.677000,69.102000,76.270000,7.168000,1.472000,0.657000,2.440000,1.783000
Caribbean small states,72.579204,69.777390,75.467188,5.689799,0.055794,-0.006135,0.123953,0.130088
World,72.243850,69.799734,74.857330,5.057596,-0.735866,-0.823878,-0.612678,0.211200
St. Vincent and the Grenadines,72.126000,69.812000,74.944000,5.132000,-0.709000,-0.721000,-0.636000,0.085000
Jamaica,71.869000,69.818000,73.918000,4.100000,0.102000,0.150000,0.044000,-0.106000
Guatemala,71.797000,68.258000,75.545000,7.287000,-1.332000,-2.181000,-0.267000,1.914000
Nicaragua,71.795000,68.648000,75.012000,6.364000,-2.259000,-2.418000,-1.989000,0.429000
Greenland,71.636829,69.710000,73.660000,3.950000,-0.406829,-0.480000,-0.330000,0.150000
St. Kitts and Nevis,71.627000,68.322000,75.266000,6.944000,0.055000,0.028000,0.071000,0.043000
Honduras,71.462000,69.126000,73.987000,4.861000,-1.419000,-1.408000,-1.383000,0.025000
El Salvador,71.061000,66.432000,75.413000,8.981000,-1.498000,-1.577000,-1.363000,0.214000
Mexico,70.133000,66.334000,74.314000,7.980000,-4.069000,-4.597000,-3.260000,1.337000
Haiti,64.052000,61.131000,67.118000,5.987000,-0.203000,-0.183000,-0.211000,-0.028000

In [16]:
table_code_N_America = create_table(df_N_America)
output_table_code(table_code_N_America, 'Table code WBG -2020 -N_America -en.txt', destination='file')

Data has written to file

In [17]:
table_code_N_America = create_table(df_N_America, lang='ru')
output_table_code(table_code_N_America, 'Table code WBG -2020 -N_America -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [18]:
dd_S_America = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador',
                'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela',
                'World']

df_S_America = df.loc[dd_S_America]  \
                 .sort_values(by='total', ascending=False)
df_S_America

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Chile,79.37700,76.745000,82.04100,5.296000,-0.949000,-1.149000,-0.670000,0.4790
Uruguay,78.43000,74.688000,81.91100,7.223000,0.922000,1.109000,0.615000,-0.4940
Argentina,75.89200,72.546000,79.28500,6.739000,-1.392000,-1.311000,-1.396000,-0.0850
Colombia,74.76900,71.537000,78.13600,6.599000,-1.983000,-2.263000,-1.585000,0.6780
Brazil,74.00900,70.700000,77.37500,6.675000,-1.329000,-1.503000,-1.094000,0.4090
Peru,73.66500,70.808000,76.81600,6.008000,-2.491000,-3.096000,-1.681000,1.4150
Paraguay,73.18200,70.398000,76.15600,5.758000,-0.439000,-0.563000,-0.285000,0.2780
Suriname,72.56100,69.264000,75.98100,6.717000,0.319000,0.320000,0.301000,-0.0190
World,72.24385,69.799734,74.85733,5.057596,-0.735866,-0.823878,-0.612678,0.2112
Ecuador,72.15300,68.765000,76.05600,7.291000,-5.144000,-5.934000,-3.897000,2.0370
Venezuela,71.09500,66.739000,75.81400,9.075000,-1.066000,-1.295000,-0.752000,0.5430
Guyana,68.48600,65.075000,72.11800,7.043000,-0.638000,-0.731000,-0.540000,0.1910
Bolivia,64.46700,61.559000,67.84100,6.282000,-3.374000,-3.811000,-2.634000,1.1770

In [19]:
table_code_S_America = create_table(df_S_America)
output_table_code(table_code_S_America, 'Table code WBG -2020 -S_America -en.txt', destination='file')

Data has written to file

In [20]:
table_code_S_America = create_table(df_S_America, lang='ru')
output_table_code(table_code_S_America, 'Table code WBG -2020 -S_America -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [21]:
dd_Asia = ['Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia', 'China', 'Cyprus', 'Egypt',
           'Georgia', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'North Korea', 'South Korea',
           'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal', 'Oman', 'Pakistan',
           'Philippines', 'Qatar', 'Russia', 'Saudi Arabia', 'Singapore', 'Sri Lanka', 'Syria', 'Tajikistan', 'Thailand', 'Timor-Leste',
           'Turkey', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen', 'Palestine',
           'World']  # 'Europe & Central Asia', 'South Asia', 'East Asia & Pacific', 'Middle East & North Africa'

df_Asia = df.loc[dd_Asia]   \
            .sort_values(by='total', ascending=False)
df_Asia

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Japan,84.560000,81.560000,87.71000,6.150000,0.203659,0.150000,0.260000,0.1100
Singapore,84.465854,83.100000,85.90000,2.800000,0.870732,1.700000,0.000000,-1.7000
South Korea,83.426829,80.500000,86.50000,6.000000,0.200000,0.200000,0.200000,0.0000
Israel,82.648780,80.600000,84.80000,4.200000,-0.156098,-0.400000,0.100000,0.5000
Cyprus,81.391000,79.345000,83.44800,4.103000,-0.006000,-0.163000,0.178000,0.3410
Maldives,79.875000,78.850000,81.27300,2.423000,-0.241000,-0.473000,0.111000,0.5840
Thailand,79.274000,74.954000,83.69700,8.743000,0.299000,0.316000,0.264000,-0.0520
Bahrain,79.174000,78.165000,80.43300,2.268000,-0.845000,-0.815000,-0.886000,-0.0710
Qatar,79.099000,78.225000,80.67900,2.454000,-1.891000,-1.839000,-1.967000,-0.1280
United Arab Emirates,78.946000,77.464000,81.11200,3.648000,-0.780000,-0.711000,-0.795000,-0.0840
China,78.077000,75.305000,81.05800,5.753000,0.109000,0.007000,0.242000,0.2350
Lebanon,77.804000,75.637000,79.89500,4.258000,-1.432000,-1.614000,-1.148000,0.4660
Kuwait,76.920000,75.350000,80.02300,4.673000,-2.765000,-2.899000,-2.243000,0.6560
Sri Lanka,76.393000,72.597000,80.11100,7.514000,0.385000,0.370000,0.368000,-0.0020
Saudi Arabia,76.239000,74.966000,77.99200,3.026000,-1.065000,-1.104000,-0.917000,0.1870
Malaysia,75.938000,73.648000,78.47200,4.824000,0.178000,0.183000,0.166000,-0.0170
Turkey,75.850000,72.772000,79.06100,6.289000,-1.982000,-1.908000,-1.892000,0.0160
Vietnam,75.378000,70.787000,79.92000,9.133000,1.285000,1.418000,1.032000,-0.3860
Jordan,75.184000,72.987000,77.77200,4.785000,-0.860000,-0.907000,-0.734000,0.1730
Iran,74.832000,72.102000,77.81700,5.715000,-1.271000,-1.277000,-1.238000,0.0390
Brunei,74.795000,72.749000,77.03300,4.284000,0.047000,0.043000,0.047000,0.0040
Oman,74.757000,73.289000,76.78800,3.499000,-3.245000,-3.254000,-3.159000,0.0950
Palestine,74.403000,72.164000,76.68300,4.519000,-0.838000,-0.964000,-0.655000,0.3090
North Korea,73.274000,70.793000,75.72500,4.932000,0.076000,0.168000,0.025000,-0.1430
Georgia,72.765000,67.740000,77.87400,10.134000,-0.705000,-0.753000,-0.555000,0.1980
World,72.243850,69.799734,74.85733,5.057596,-0.735866,-0.823878,-0.612678,0.2112
Armenia,72.173000,67.051000,76.99600,9.945000,-3.266000,-3.352000,-2.860000,0.4920
Mongolia,72.141000,67.502000,77.02000,9.518000,0.319000,0.248000,0.375000,0.1270
Syria,72.140000,68.888000,75.55500,6.667000,0.318000,0.664000,-0.083000,-0.7470
Philippines,72.119000,70.244000,73.99700,3.753000,0.254000,0.258000,0.255000,-0.0030
Bangladesh,71.968000,70.187000,73.95700,3.770000,-0.838000,-0.526000,-1.133000,-0.6070
Kyrgyzstan,71.800000,67.800000,76.00000,8.200000,0.200000,0.200000,0.200000,0.0000
Bhutan,71.609000,69.965000,73.53600,3.571000,0.218000,0.152000,0.300000,0.1480
Kazakhstan,71.370000,67.090000,75.53000,8.440000,-1.810000,-1.730000,-1.770000,-0.0400
Russia,71.338780,66.490000,76.43000,9.940000,-1.745122,-1.750000,-1.740000,0.0100
Egypt,70.990000,68.667000,73.39000,4.723000,-0.368000,-0.382000,-0.321000,0.0610
Cambodia,70.416000,67.999000,72.72400,4.725000,-0.276000,-0.401000,-0.149000,0.2520
Uzbekistan,70.331000,67.876000,72.78900,4.913000,-1.013000,-0.906000,-1.094000,-0.1880
India,70.150000,68.615000,71.82400,3.209000,-0.760000,-0.910000,-0.571000,0.3390
Nepal,69.246000,67.345000,71.17300,3.828000,-0.312000,-0.410000,-0.178000,0.2320
Iraq,69.123000,66.954000,71.18500,4.231000,-2.453000,-2.605000,-2.243000,0.3620
Indonesia,68.808000,66.745000,70.98200,4.237000,-1.710000,-1.736000,-1.615000,0.1210
Turkmenistan,68.687000,65.392000,71.98400,6.592000,-0.315000,-0.160000,-0.480000,-0.3200
Laos,68.497000,66.519000,70.59400,4.075000,0.359000,0.364000,0.360000,-0.0040
Timor-Leste,68.475000,66.837000,70.27900,3.442000,0.207000,0.116000,0.329000,0.2130
Tajikistan,67.994000,65.999000,70.17000,4.171000,-2.873000,-2.863000,-2.840000,0.0230
Azerbaijan,66.868000,62.986000,70.99800,8.012000,-6.234000,-7.244000,-4.834000,2.4100
Myanmar,66.797000,63.785000,69.95900,6.174000,0.187000,0.213000,0.160000,-0.0530
Pakistan,66.269000,63.945000,68.82500,4.880000,-0.487000,-0.650000,-0.271000,0.3790
Yemen,64.650000,61.636000,67.88500,6.249000,-0.442000,-0.171000,-0.742000,-0.5710
Afghanistan,62.575000,59.866000,65.43200,5.566000,-0.990000,-0.753000,-1.245000,-0.4920

In [22]:
table_code_Asia = create_table(df_Asia)
output_table_code(table_code_Asia, 'Table code WBG -2020 -Asia -en.txt', destination='file')

Data has written to file

In [23]:
table_code_Asia = create_table(df_Asia, lang='ru')
output_table_code(table_code_Asia, 'Table code WBG -2020 -Asia -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [24]:
dd_Europe = ['Albania', 'Armenia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus',
             'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy',
             'Kazakhstan', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Moldova', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway',
             'Poland', 'Portugal', 'Romania', 'Russia', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland',
             'Turkey', 'Ukraine', 'United Kingdom', 'Liechtenstein',
             'World', 'European Union',
             'Channel Islands', 'Faroe Islands', 'Gibraltar', 'Isle of Man']  # 'Central Europe and the Baltics', 'Europe & Central Asia']
# small countries: Andorra, Liechtenstein, Monaco, San Marino, Vatican City

df_Europe = df.loc[dd_Europe]   \
              .sort_values(by='total', ascending=False)
df_Europe

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Norway,83.209756,81.600000,84.900000,3.300000,0.251220,0.300000,0.200000,-1.000000e-01
Faroe Islands,83.197561,81.100000,85.400000,4.300000,0.251220,0.300000,0.200000,-1.000000e-01
Iceland,83.063415,81.600000,84.600000,3.000000,-0.100000,-0.100000,-0.100000,0.000000e+00
Switzerland,83.000000,81.000000,85.100000,4.100000,-0.904878,-1.100000,-0.700000,4.000000e-01
Ireland,82.556098,80.800000,84.400000,3.600000,-0.146341,0.000000,-0.300000,-3.000000e-01
Sweden,82.356098,80.600000,84.200000,3.600000,-0.753659,-0.900000,-0.600000,3.000000e-01
Malta,82.348780,80.300000,84.500000,4.200000,-0.509756,-0.900000,-0.100000,8.000000e-01
Spain,82.331707,79.600000,85.200000,5.600000,-1.500000,-1.500000,-1.500000,0.000000e+00
Gibraltar,82.198000,80.249000,84.112000,3.863000,-0.165000,-0.125000,-0.176000,-5.100000e-02
Italy,82.195122,80.000000,84.500000,4.500000,-1.302439,-1.400000,-1.200000,2.000000e-01
France,82.175610,79.200000,85.300000,6.100000,-0.651220,-0.700000,-0.600000,1.000000e-01
Luxembourg,82.143902,79.900000,84.500000,4.600000,-0.495122,-0.300000,-0.700000,-4.000000e-01
Finland,81.931707,79.200000,84.800000,5.600000,-0.051220,-0.100000,0.000000,1.000000e-01
Liechtenstein,81.658537,80.000000,83.400000,3.400000,-2.502439,-2.600000,-2.400000,2.000000e-01
Denmark,81.602439,79.700000,83.600000,3.900000,0.151220,0.200000,0.100000,-1.000000e-01
Cyprus,81.391000,79.345000,83.448000,4.103000,-0.006000,-0.163000,0.178000,3.410000e-01
Netherlands,81.358537,79.700000,83.100000,3.400000,-0.753659,-0.900000,-0.600000,3.000000e-01
Greece,81.287805,78.800000,83.900000,5.100000,-0.351220,-0.400000,-0.300000,1.000000e-01
Channel Islands,81.264000,79.141000,83.387000,4.246000,-0.126000,-0.125000,-0.112000,1.300000e-02
Austria,81.192683,78.900000,83.600000,4.700000,-0.702439,-0.800000,-0.600000,2.000000e-01
Germany,81.041463,78.700000,83.500000,4.800000,-0.251220,-0.300000,-0.200000,1.000000e-01
Portugal,80.975610,78.000000,84.100000,6.100000,-0.700000,-0.700000,-0.700000,0.000000e+00
Belgium,80.695122,78.500000,83.000000,4.500000,-1.300000,-1.300000,-1.300000,0.000000e+00
Isle of Man,80.588000,78.672000,82.536000,3.864000,-0.149000,-0.185000,-0.093000,9.200000e-02
Slovenia,80.531707,77.800000,83.400000,5.600000,-0.997561,-0.900000,-1.100000,-2.000000e-01
European Union,80.452093,77.735582,83.317874,5.582291,-0.862765,-0.930323,-0.791189,1.391343e-01
United Kingdom,80.351220,78.400000,82.400000,4.000000,-1.053659,-1.200000,-0.900000,3.000000e-01
Estonia,78.595122,74.400000,83.000000,8.600000,-0.051220,-0.100000,0.000000,1.000000e-01
Czechia,78.226829,75.300000,81.300000,6.000000,-1.002439,-1.100000,-0.900000,2.000000e-01
Croatia,77.724390,74.700000,80.900000,6.200000,-0.700000,-0.700000,-0.700000,1.421085e-14
Albania,76.989000,74.632000,79.676000,5.044000,-2.293000,-2.536000,-1.990000,5.460000e-01
Slovakia,76.865854,73.500000,80.400000,6.900000,-0.800000,-0.800000,-0.800000,0.000000e+00
Poland,76.500000,72.500000,80.700000,8.200000,-1.404878,-1.600000,-1.200000,4.000000e-01
Bosnia and Herzegovina,76.225000,74.040000,78.414000,4.374000,-1.016000,-1.168000,-0.806000,3.620000e-01
Montenegro,75.931707,73.200000,78.800000,5.600000,-0.751220,-0.800000,-0.700000,1.000000e-01
Turkey,75.850000,72.772000,79.061000,6.289000,-1.982000,-1.908000,-1.892000,1.600000e-02
Hungary,75.568293,72.300000,79.000000,6.700000,-0.751220,-0.800000,-0.700000,1.000000e-01
Latvia,75.185366,70.600000,80.000000,9.400000,-0.202439,-0.300000,-0.100000,2.000000e-01
Lithuania,74.978049,70.100000,80.100000,10.000000,-1.304878,-1.500000,-1.100000,4.000000e-01
Serbia,74.478049,71.600000,77.500000,5.900000,-1.458537,-1.800000,-1.100000,7.000000e-01
North Macedonia,74.395122,72.200000,76.700000,4.500000,-2.207317,-2.500000,-1.900000,6.000000e-01
Romania,74.253659,70.400000,78.300000,7.900000,-1.353659,-1.500000,-1.200000,3.000000e-01
Bulgaria,73.658537,70.000000,77.500000,7.500000,-1.453659,-1.600000,-1.300000,3.000000e-01
Georgia,72.765000,67.740000,77.874000,10.134000,-0.705000,-0.753000,-0.555000,1.980000e-01
Belarus,72.457220,67.306000,77.866000,10.560000,-1.769610,-1.994000,-1.534000,4.600000e-01
World,72.243850,69.799734,74.857330,5.057596,-0.735866,-0.823878,-0.612678,2.111999e-01
Armenia,72.173000,67.051000,76.996000,9.945000,-3.266000,-3.352000,-2.860000,4.920000e-01
Kazakhstan,71.370000,67.090000,75.530000,8.440000,-1.810000,-1.730000,-1.770000,-4.000000e-02
Russia,71.338780,66.490000,76.430000,9.940000,-1.745122,-1.750000,-1.740000,1.000000e-02
Ukraine,71.185122,66.390000,76.220000,9.830000,-0.642195,-0.530000,-0.760000,-2.300000e-01
Moldova,70.166000,65.692000,74.852000,9.160000,-0.769000,-0.686000,-0.765000,-7.900000e-02
Azerbaijan,66.868000,62.986000,70.998000,8.012000,-6.234000,-7.244000,-4.834000,2.410000e+00

In [25]:
table_code_Europe = create_table(df_Europe)
output_table_code(table_code_Europe, 'Table code WBG -2020 -Europe -en.txt', destination='file')

Data has written to file

In [26]:
table_code_Europe = create_table(df_Europe, lang='ru')
output_table_code(table_code_Europe, 'Table code WBG -2020 -Europe -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [27]:
dd_Africa = ['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cameroon', 'Cabo Verde',
             "Cote d'Ivoire", 'Central African Republic', 'Chad', 'Comoros', 'DR Congo',
             'Congo, Rep.', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini',
             'Ethiopia', 'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya',
             'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius',
             'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Sao Tome and Principe',
             'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan',
             'Tanzania', 'Togo', 'Tunisia', 'Uganda', 'Zambia', 'Zimbabwe',
             'World']  # 'Middle East & North Africa', 'Africa Eastern and Southern', 'Sub-Saharan Africa', 'Africa Western and Central'

df_Africa = df.loc[dd_Africa]   \
              .sort_values(by='total', ascending=False)
df_Africa

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Seychelles,77.236585,72.700000,82.00000,9.300000,3.190244,2.800000,3.600000,0.8000
Tunisia,75.292000,71.837000,79.27900,7.442000,-0.701000,-1.058000,-0.100000,0.9580
Cabo Verde,74.808000,70.333000,79.16000,8.827000,-1.196000,-1.237000,-1.023000,0.2140
Algeria,74.453000,73.082000,75.91200,2.830000,-2.021000,-2.156000,-1.848000,0.3080
Mauritius,74.177073,70.860000,77.66000,6.800000,-0.058780,-0.210000,0.100000,0.3100
Morocco,73.920000,71.757000,76.30800,4.551000,-0.350000,-0.488000,-0.140000,0.3480
Libya,72.472000,69.867000,75.34800,5.481000,0.009000,0.371000,-0.418000,-0.7890
World,72.243850,69.799734,74.85733,5.057596,-0.735866,-0.823878,-0.612678,0.2112
Egypt,70.990000,68.667000,73.39000,4.723000,-0.368000,-0.382000,-0.321000,0.0610
Senegal,68.006000,65.587000,70.27100,4.684000,-0.520000,-0.360000,-0.683000,-0.3230
Sao Tome and Principe,67.785000,65.160000,70.87800,5.718000,-0.738000,-0.671000,-0.742000,-0.0710
Eritrea,67.133000,64.862000,69.33700,4.475000,-0.167000,-0.354000,0.028000,0.3820
Rwanda,66.774000,64.358000,68.99600,4.638000,0.337000,0.178000,0.516000,0.3380
Gabon,66.531000,64.258000,69.11600,4.858000,-0.072000,-0.323000,0.251000,0.5740
Tanzania,66.408000,64.373000,68.54200,4.169000,-0.581000,-0.548000,-0.575000,-0.0270
Botswana,65.647000,63.142000,68.05100,4.909000,0.183000,0.208000,0.160000,-0.0480
Sudan,65.614000,63.106000,68.20800,5.102000,-0.262000,-0.326000,-0.180000,0.1460
Ethiopia,65.371000,62.517000,68.42600,5.909000,-0.467000,-0.534000,-0.369000,0.1650
South Africa,65.252000,62.178000,67.96400,5.786000,-0.923000,-0.656000,-1.143000,-0.4870
Madagascar,65.182000,62.891000,67.61200,4.721000,-0.700000,-0.771000,-0.598000,0.1730
Mauritania,64.532000,62.781000,66.33500,3.554000,-1.155000,-0.996000,-1.316000,-0.3200
Comoros,64.166000,61.975000,66.59300,4.618000,0.098000,-0.034000,0.287000,0.3210
Ghana,64.114000,61.900000,66.38500,4.485000,-0.626000,-0.786000,-0.440000,0.3460
"Congo, Rep.",63.785000,62.212000,65.39700,3.185000,1.038000,0.866000,1.232000,0.3660
Malawi,63.717000,60.014000,67.59700,7.583000,-0.402000,-0.388000,-0.371000,0.0170
Uganda,62.851000,60.715000,64.89800,4.183000,-0.140000,-0.178000,-0.092000,0.0860
Namibia,62.829000,59.058000,66.60600,7.548000,-0.246000,-0.368000,-0.031000,0.3370
Djibouti,62.694000,60.071000,65.46100,5.390000,-0.391000,-0.624000,-0.102000,0.5220
Kenya,62.675000,60.372000,65.06200,4.690000,-0.268000,-0.306000,-0.213000,0.0930
Gambia,62.612000,61.023000,64.23500,3.212000,-1.143000,-1.307000,-0.951000,0.3560
Zambia,62.380000,59.643000,65.04300,5.400000,-0.413000,-0.437000,-0.366000,0.0710
Angola,62.261000,59.584000,64.98200,5.398000,-0.187000,-0.393000,0.060000,0.4530
Burundi,61.566000,59.465000,63.67500,4.210000,-0.785000,-0.874000,-0.672000,0.2020
Niger,61.451000,60.472000,62.45400,1.982000,-1.446000,-1.396000,-1.485000,-0.0890
Mozambique,61.172000,58.111000,64.16000,6.049000,0.006000,-0.201000,0.240000,0.4410
Zimbabwe,61.124000,58.129000,63.86200,5.733000,-0.168000,-0.515000,0.201000,0.7160
Togo,61.035000,60.486000,61.57600,1.090000,0.134000,0.136000,0.133000,-0.0030
Liberia,60.948000,59.528000,62.35500,2.827000,-0.156000,-0.364000,0.057000,0.4210
Cameroon,60.833000,59.081000,62.63300,3.552000,-0.751000,-1.105000,-0.363000,0.7420
Equatorial Guinea,60.708000,58.812000,62.94300,4.131000,-0.936000,-1.172000,-0.597000,0.5750
Benin,60.088000,58.693000,61.48500,2.792000,-0.366000,-0.357000,-0.373000,-0.0160
Guinea-Bissau,59.999000,57.612000,62.26500,4.653000,-0.883000,-1.151000,-0.607000,0.5440
Sierra Leone,59.763000,58.404000,61.11600,2.712000,-0.492000,-0.537000,-0.438000,0.0990
DR Congo,59.739000,57.818000,61.70000,3.882000,-0.537000,-0.517000,-0.543000,-0.0260
Burkina Faso,59.731000,57.787000,61.59800,3.811000,-0.308000,-0.386000,-0.224000,0.1620
Eswatini,59.692000,56.026000,63.67800,7.652000,-0.857000,-0.949000,-0.675000,0.2740
Guinea,59.327000,58.113000,60.44900,2.336000,-0.393000,-0.431000,-0.368000,0.0630
Cote d'Ivoire,59.032000,57.860000,60.35100,2.491000,-0.287000,-0.302000,-0.239000,0.0630
Mali,58.633000,57.385000,59.94000,2.555000,-1.031000,-1.138000,-0.901000,0.2370
Somalia,55.967000,53.967000,58.05100,4.084000,-1.111000,-1.155000,-1.041000,0.1140
South Sudan,55.480000,53.906000,56.99800,3.092000,-0.432000,-0.565000,-0.292000,0.2730
Lesotho,54.693000,51.962000,57.53700,5.575000,0.520000,0.556000,0.484000,-0.0720
Central African Republic,54.604000,52.582000,56.75700,4.175000,-0.421000,-0.466000,-0.349000,0.1170
Nigeria,52.887000,52.456000,53.32300,0.867000,-0.023000,-0.195000,0.158000,0.3530
Chad,52.777000,51.218000,54.39600,3.178000,-0.482000,-0.446000,-0.512000,-0.0660

In [28]:
table_code_Africa = create_table(df_Africa)
output_table_code(table_code_Africa, 'Table code WBG -2020 -Africa -en.txt', destination='file')

Data has written to file

In [29]:
table_code_Africa = create_table(df_Africa, lang='ru')
output_table_code(table_code_Africa, 'Table code WBG -2020 -Africa -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [30]:
dd_Oceania = ['Australia', 'Papua New Guinea', 'New Zealand', 'Fiji', 'Solomon Islands', 'Vanuatu',
              'Samoa', 'Kiribati', 'Micronesia', 'Tonga', 'Marshall Islands', 'Nauru', 'Tuvalu',
              'French Polynesia', 'New Caledonia', 'Guam', 'Pacific island small states',
              'World']
# Database does not contain data for 'Palau', 'American Samoa', 'Northern Mariana Islands'

df_Oceania = df.loc[dd_Oceania]   \
                 .sort_values(by='total', ascending=False)
df_Oceania

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Australia,83.200000,81.200000,85.300000,4.100000,0.300000,0.300000,0.300000,0.000000e+00
New Zealand,82.256098,80.500000,84.100000,3.600000,0.200000,0.200000,0.200000,-1.421085e-14
French Polynesia,82.217000,79.321000,85.834000,6.513000,-0.779000,-1.383000,0.226000,1.609000e+00
New Caledonia,80.834951,77.253000,84.596000,7.343000,0.415244,0.445000,0.384000,-6.100000e-02
Guam,76.612000,72.197000,81.868000,9.671000,-1.105000,-1.967000,0.292000,2.259000e+00
Samoa,72.768000,70.341000,75.459000,5.118000,0.611000,0.574000,0.654000,8.000000e-02
World,72.243850,69.799734,74.857330,5.057596,-0.735866,-0.823878,-0.612678,2.111999e-01
Tonga,70.928000,68.337000,73.698000,5.361000,0.057000,0.072000,0.029000,-4.300000e-02
Micronesia,70.674000,67.106000,74.540000,7.434000,-0.403000,-0.475000,-0.302000,1.730000e-01
Vanuatu,70.299000,68.547000,72.427000,3.880000,0.422000,0.746000,0.022000,-7.240000e-01
Solomon Islands,70.199000,68.791000,71.802000,3.011000,-0.183000,-0.241000,-0.098000,1.430000e-01
Pacific island small states,69.364921,67.521909,71.373408,3.851499,0.070670,0.089229,0.048091,-4.113813e-02
Fiji,67.924000,66.166000,69.743000,3.577000,0.031000,0.040000,0.015000,-2.500000e-02
Kiribati,67.266000,65.348000,68.948000,3.600000,0.116000,0.053000,0.166000,1.130000e-01
Papua New Guinea,65.787000,63.395000,68.804000,5.409000,0.313000,0.432000,0.133000,-2.990000e-01
Marshall Islands,64.977000,63.426000,66.882000,3.456000,0.231000,0.193000,0.274000,8.100000e-02
Tuvalu,64.382000,60.670000,68.978000,8.308000,0.104000,0.078000,0.128000,5.000000e-02
Nauru,63.437000,59.994000,67.272000,7.278000,-0.047000,-0.061000,-0.049000,1.200000e-02

In [31]:
table_code_Oceania = create_table(df_Oceania)
output_table_code(table_code_Oceania, 'Table code WBG -2020 -Oceania -en.txt', destination='file')

Data has written to file

In [32]:
table_code_Oceania = create_table(df_Oceania, lang='ru')
output_table_code(table_code_Oceania, 'Table code WBG -2020 -Oceania -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [33]:
dd_CIS = ['Armenia', 'Azerbaijan', 'Belarus', 'Kazakhstan', 'Kyrgyzstan', 'Moldova',
          'Russia', 'Tajikistan', 'Uzbekistan', 'Turkmenistan']  # 'Georgia', 'Ukraine'

df_CIS = df.loc[dd_CIS]   \
           .sort_values(by='total', ascending=False)
df_CIS

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
Belarus,72.45722,67.306,77.866,10.560,-1.769610,-1.994,-1.534,0.460
Armenia,72.17300,67.051,76.996,9.945,-3.266000,-3.352,-2.860,0.492
Kyrgyzstan,71.80000,67.800,76.000,8.200,0.200000,0.200,0.200,0.000
Kazakhstan,71.37000,67.090,75.530,8.440,-1.810000,-1.730,-1.770,-0.040
Russia,71.33878,66.490,76.430,9.940,-1.745122,-1.750,-1.740,0.010
Uzbekistan,70.33100,67.876,72.789,4.913,-1.013000,-0.906,-1.094,-0.188
Moldova,70.16600,65.692,74.852,9.160,-0.769000,-0.686,-0.765,-0.079
Turkmenistan,68.68700,65.392,71.984,6.592,-0.315000,-0.160,-0.480,-0.320
Tajikistan,67.99400,65.999,70.170,4.171,-2.873000,-2.863,-2.840,0.023
Azerbaijan,66.86800,62.986,70.998,8.012,-6.234000,-7.244,-4.834,2.410

In [34]:
table_code_CIS = create_table(df_CIS)
output_table_code(table_code_CIS, 'Table code WBG -2020 -CIS -en.txt', destination='file')

Data has written to file

In [35]:
table_code_CIS = create_table(df_CIS, lang='ru')
output_table_code(table_code_CIS, 'Table code WBG -2020 -CIS -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [36]:
ls_regions = [
    'European Union', 'Central Europe and the Baltics',
    'Europe & Central Asia',
    'South Asia',
    'East Asia & Pacific',
    'Middle East & North Africa',
    'Africa Eastern and Southern', 'Sub-Saharan Africa', 'Africa Western and Central',
    'North America', 'Latin America & Caribbean',
    'Arab World'
]

# exclude countries with population <50,000
ls_dropped_territories = ['St. Kitts and Nevis', 'Turks and Caicos Islands', 'Sint Maarten', 'Gibraltar',
                          'Collectivity of Saint Martin', 'British Virgin Islands', 'Tuvalu', 'Nauru']  # 'Palau'

In [37]:
df_all_countries = df.drop(ls_regions + ls_dropped_territories)
print(len(df_all_countries))

201

In [38]:
table_code_all_countries = create_table(df_all_countries)
output_table_code(table_code_all_countries, 'Table code WBG -2020 -all_countries -en.txt', destination='file')

Data has written to file

In [39]:
table_code_all_countries = create_table(df_all_countries, lang='ru')
output_table_code(table_code_all_countries, 'Table code WBG -2020 -all_countries -ru.txt', destination='file')

Data has written to file

<br />
<br />
<br />

In [40]:
# create code for placing info in Wikipedia
def create_table_for_regions(df, lang='en'):

    if lang=='ru':
        file_header='wbg_stats_header_2020_ru.txt'
        ptn_1 = 'флагификация'
        ptn_2 = 'флаг'
        prettify_name = {
            'European Union': '[[Европейский союз]]',
            'Central Europe and the Baltics': '[[Центральная Европа]] и [[Прибалтика]]',
            'Europe & Central Asia': '[[Европа]] и [[Центральная Азия]]',
            'South Asia': '[[Южная Азия]]',
            'East Asia & Pacific': '[[Восточная Азия]] и [[Австралия и Океания|Океания]]',
            'Middle East & North Africa': '[[Страны MENA|Ближний Восток и Северная Африка]]',
            'Africa Eastern and Southern': '[[Восточная Африка|Восточная]] и [[Южная Африка|Южная]] Африка',
            'Sub-Saharan Africa': '[[Чёрная Африка|Африка к югу от Сахары]]',
            'Africa Western and Central': '[[Западная Африка|Западная]] и [[Центральная Африка|Центральная]] Африка',
            'North America': '[[Северная Америка]]',
            'Latin America & Caribbean': '[[Латинская Америка]] и [[Антильские острова|Карибы]]',
            'Arab World': 'Арабский мир',
            'World': 'Мир'
        }
    else:
        file_header='wbg_stats_header_2020_en.txt'
        ptn_1 = 'flaglist'
        ptn_2 = 'flagicon'
        prettify_name = {
            'European Union': '[[European Union]]',
            'Central Europe and the Baltics': '[[Central Europe]] & the [[Baltic states|Baltics]]',
            'Europe & Central Asia': '[[Europe]] & [[Central Asia]]',
            'South Asia': '[[South Asia]]',
            'East Asia & Pacific': '[[Asia-Pacific|East Asia & Pacific]]',
            'Middle East & North Africa': '[[MENA|Middle East & North Africa]]',
            'Africa Eastern and Southern': 'Africa [[East Africa|Eastern]] & [[Southern Africa|Southern]]',
            'Sub-Saharan Africa': '[[Sub-Saharan Africa]]',
            'Africa Western and Central': 'Africa [[West Africa|Western]] & [[Central Africa|Central]]',
            'North America': '[[North America]]',
            'Latin America & Caribbean': '[[Latin America and the Caribbean|Latin America & Caribbean]]'
        }
        
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st = fh.read()
        
    st = st.strip()
        
    for i in range(len(df)):
        ser = df.iloc[i]
        if ser.name in ['World']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|align=center| \'\'\'{prettify_name.get(ser.name, ser.name)}\'\'\' ' + \
                  f'||style="text-align:center; background:#e0ffd8;"| \'\'\'{ser.total:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| \'\'\'{ser.male:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#fee7f6;"| \'\'\'{ser.female:0.2f}\'\'\' ' + \
                  f'||style="text-align:center;"| \'\'\'{ser.gender_gap:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#e0ffd8; border-left-width:2px;"| \'\'\'{ser.Δ_2019_total:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| \'\'\'{ser.Δ_2019_male:0.2f}\'\'\' ' + \
                  f'||style="text-align:center; background:#fee7f6;"| \'\'\'{ser.Δ_2019_female:0.2f}\'\'\' ' + \
                  f'||style="text-align:center;"| \'\'\'{ser.Δ_2019_gender_gap:0.2f}\'\'\''
        else:
            st += '\n' + '|-\n' + \
                  f'|align=left|{prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="text-align:center; background:#e0ffd8;"| {ser.total:0.2f} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {ser.male:0.2f} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {ser.female:0.2f} ' + \
                  f'||style="text-align:center;"| {ser.gender_gap:0.2f} ' + \
                  f'||style="text-align:center; background:#e0ffd8; border-left-width:2px;"| {ser.Δ_2019_total:0.2f} ' + \
                  f'||style="text-align:center; background:#eaf3ff;"| {ser.Δ_2019_male:0.2f} ' + \
                  f'||style="text-align:center; background:#fee7f6;"| {ser.Δ_2019_female:0.2f} ' + \
                  f'||style="text-align:center;"| {ser.Δ_2019_gender_gap:0.2f}'
    st += '\n|}'

    if lang == 'ru':
        st = re.sub('(?<=\d)\.(?=\d)', ',', st)  # replace . to comma, if this . is between two digits

    return st

In [41]:
df_regions = df.loc[ls_regions + ['World']]   \
               .sort_values(by='total', ascending=False)
df_regions

,total,male,female,gender_gap,Δ_2019_total,Δ_2019_male,Δ_2019_female,Δ_2019_gender_gap
,,,,,,,,
European Union,80.452093,77.735582,83.317874,5.582291,-0.862765,-0.930323,-0.791189,0.139134
North America,77.463872,74.746275,80.317669,5.571394,-1.677840,-1.953443,-1.388346,0.565097
Europe & Central Asia,76.959190,73.841057,80.275346,6.434289,-1.227058,-1.269519,-1.158177,0.111342
East Asia & Pacific,76.761940,73.993839,79.700041,5.706202,-0.035835,-0.092787,0.040677,0.133464
Central Europe and the Baltics,76.087717,72.395227,79.974126,7.578899,-1.179128,-1.309201,-1.041954,0.267247
Latin America & Caribbean,73.038474,69.670039,76.596316,6.926278,-1.999875,-2.284248,-1.578995,0.705253
Middle East & North Africa,72.949768,70.812576,75.321682,4.509106,-1.009347,-1.049693,-0.924720,0.124973
World,72.243850,69.799734,74.857330,5.057596,-0.735866,-0.823878,-0.612678,0.211200
Arab World,70.923360,68.936223,73.112711,4.176488,-0.921266,-0.970743,-0.826599,0.144144
South Asia,69.748331,68.044360,71.613304,3.568944,-0.724424,-0.827850,-0.587155,0.240695
Africa Eastern and Southern,63.313856,60.817480,65.836460,5.018980,-0.441818,-0.473237,-0.383261,0.089976
Sub-Saharan Africa,60.848891,58.902877,62.830381,3.927504,-0.395396,-0.461538,-0.308521,0.153016
Africa Western and Central,57.226373,56.131023,58.346240,2.215217,-0.329423,-0.446369,-0.199739,0.246630

In [42]:
table_code_regions = create_table_for_regions(df_regions)
output_table_code(table_code_regions, 'Table code WBG -2020 -z_regions -en.txt', destination='file')

Data has written to file

In [43]:
table_code_regions = create_table_for_regions(df_regions, lang='ru')
output_table_code(table_code_regions, 'Table code WBG -2020 -z_regions -ru.txt', destination='file')

Data has written to file